// Fallout Shelter Game Constants
// These values represent the actual limits and constraints from the game

// --------- NOTES ---------
// The game handles 2,147,483,648 as -2,147,483,648, which is quite literally infinity in-game

export const GAME_LIMITS = {
  // Vault limits
  VAULT_NAME_MAX_LENGTH: 50,
  
  // Currency
  CAPS_MAX: 2147483648,
  NUKA_COLA_MAX: 2147483648,

  // Items
  LUNCHBOXES_MAX: 999,
  MR_HANDIES_MAX: 999,
  PET_CARRIERS_MAX: 999,
  STARTER_PACKS_MAX: 999,
  
  // Resources
  FOOD_MAX: 2147483648,
  WATER_MAX: 2147483648,
  ENERGY_MAX: 2147483648,

  // Health Resources
  RADAWAY_MAX: 2147483648,
  STIMPACKS_MAX: 2147483648,
  
  // Dweller stats
  SPECIAL_MIN: 0,
  SPECIAL_MAX: 10,
  HAPPINESS_MIN: 0,
  HAPPINESS_MAX: 100,
  HEALTH_MIN: 0,
  HEALTH_MAX: 100,
  LEVEL_MIN: 1,
  LEVEL_MAX: 50,
  RADIATION_MIN: 0,
  RADIATION_MAX: 100,
  
  // Vault configuration
  VAULT_THEMES: {
    NORMAL: 0,
    CHRISTMAS: 1,
    HALLOWEEN: 2,
    THANKSGIVING: 3
  } as const,
  
  VAULT_MODES: {
    NORMAL: 'Normal',
    SURVIVAL: 'Survival'
  } as const
} as const;

// SPECIAL stat names for UI display
export const SPECIAL_STAT_NAMES = [
  'Unknown',
  'Strength',     // S
  'Perception',   // P
  'Endurance',    // E
  'Charisma',     // C
  'Intelligence', // I
  'Agility',      // A
  'Luck'          // L
] as const;

// Short SPECIAL stat names for compact display
export const SPECIAL_STAT_SHORT_NAMES = [
  'Unknown',
  'S',  // Strength
  'P',  // Perception
  'E',  // Endurance
  'C',  // Charisma
  'I',  // Intelligence
  'A',  // Agility
  'L'   // Luck
] as const;

// Resource types with their display names
export const RESOURCE_TYPES = {
  CAPS: { key: 'Caps', display: 'Caps', max: GAME_LIMITS.CAPS_MAX },
  FOOD: { key: 'Food', display: 'Food', max: GAME_LIMITS.FOOD_MAX },
  WATER: { key: 'Water', display: 'Water', max: GAME_LIMITS.WATER_MAX },
  ENERGY: { key: 'Energy', display: 'Energy', max: GAME_LIMITS.ENERGY_MAX },
  RADAWAY: { key: 'RadAway', display: 'RadAway', max: GAME_LIMITS.RADAWAY_MAX },
  STIMPACK: { key: 'StimPack', display: 'Stimpacks', max: GAME_LIMITS.STIMPACKS_MAX },
  NUKA_COLA: { key: 'NukaColaQuantum', display: 'Nuka Cola Quantum', max: GAME_LIMITS.NUKA_COLA_MAX }
} as const;

// Validation functions
export const validateValue = {
  special: (value: number): number => Math.max(GAME_LIMITS.SPECIAL_MIN, Math.min(GAME_LIMITS.SPECIAL_MAX, value)),
  happiness: (value: number): number => Math.max(GAME_LIMITS.HAPPINESS_MIN, Math.min(GAME_LIMITS.HAPPINESS_MAX, value)),
  health: (value: number): number => Math.max(GAME_LIMITS.HEALTH_MIN, Math.min(GAME_LIMITS.HEALTH_MAX, value)),
  level: (value: number): number => Math.max(GAME_LIMITS.LEVEL_MIN, Math.min(GAME_LIMITS.LEVEL_MAX, value)),
  radiation: (value: number): number => Math.max(GAME_LIMITS.RADIATION_MIN, Math.min(GAME_LIMITS.RADIATION_MAX, value)),
  caps: (value: number): number => Math.max(0, Math.min(GAME_LIMITS.CAPS_MAX, value)),
  resource: (value: number, max: number): number => Math.max(0, Math.min(max, value)),
  lunchboxes: (value: number): number => Math.max(0, Math.min(GAME_LIMITS.LUNCHBOXES_MAX, value)),
  mrHandies: (value: number): number => Math.max(0, Math.min(GAME_LIMITS.MR_HANDIES_MAX, value)),
  petCarriers: (value: number): number => Math.max(0, Math.min(GAME_LIMITS.PET_CARRIERS_MAX, value)),
  starterPacks: (value: number): number => Math.max(0, Math.min(GAME_LIMITS.STARTER_PACKS_MAX, value))
} as const;

// Room unlock list
export const ROOM_UNLOCKS = [
  "RestQuartersUnlock",
  "DinerUnlock", 
  "PowerPlantUnlock",
  "WaterroomUnlock",
  "MedbayUnlock",
  "StorageUnlock",
  "RadioStationUnlock",
  "WeaponFactoryUnlock",
  "OutfitFactoryUnlock",
  "DojoUnlock",
  "ClassUnlock",
  "ArmoryUnlock",
  "FitnessUnlock",
  "BarUnlock",
  "GameRoomUnlock",
  "BarberShopUnlock",
  "HydroponicUnlock",
  "NukacolaUnlock",
  "GymUnlock",
  "SciencelabUnlock",
  "OverseerUnlock",
  "CardioUnlock",
  "DesignFactoryUnlock"
] as const;

// Recipe unlock list
export const RECIPE_UNLOCKS = [
  "Shotgun_Rusty", "Railgun", "LaserPistol_Focused", "PlasmaThrower_Boosted",
  "PlasmaThrower_Overcharged", "PipePistol_LittleBrother", "CombatShotgun_Hardened",
  "Flamer_Rusty", "LaserRifle_Tuned", "HuntingRifle_OlPainless", "PlasmaRifle_Focused",
  "PipeRifle", "JunkJet_Tactical", "InstitutePistol_Improved", "BBGun_RedRocket",
  "032Pistol_Hardened", "InstitutePistol_Apotheosis", "InstitutePistol_Scattered",
  "InstituteRifle_Excited", "PipeRifle_Long", "GatlingLaser", "PlasmaThrower_DragonsMaw",
  "PlasmaRifle", "AssaultRifle_Rusty", "AlienBlaster_Destabilizer", "Fatman_Guided",
  "Melee_RaiderSword", "SniperRifle_Hardened", "Melee_BaseballBat", "PlasmaRifle_MeanGreenMonster",
  "032Pistol_WildBillsSidearm", "GaussRifle", "LaserRifle_WaserWifle", "InstitutePistol_Scoped",
  "Flamer_Pressurized", "AssaultRifle_ArmorPiercing", "Railgun_Rusty", "Minigun_Hardened",
  "InstituteRifle_VirgilsRifle", "JunkJet_Electrified", "Flamer_Hardened", "GatlingLaser_Focused",
  "Magnum_Hardened", "Railgun_Railmaster", "Melee_PoolCue", "Minigun_Enhanced",
  "GaussRifle_Rusty", "JunkJet_RecoilCompensated", "Pistol_LoneWanderer", "MissilLauncher",
  "LaserPistol", "InstitutePistol_Incendiary", "BBGun_ArmorPiercing", "Rifle_ArmorPiercing",
  "AssaultRifle_Enhanced", "LaserRifle_Rusty", "CombatShotgun", "GatlingLaser_Tuned",
  "SawedOffShotgun_Hardened", "PlasmaThrower_Agitated", "Magnum_Blackhawk", "AssaultRifle_Infiltrator",
  "PlasmaPistol_MPLXNovasurge", "HuntingRifle_ArmorPiercing", "Railgun_Enhanced", "SniperRifle_Enhanced",
  "GaussRifle_Accelerated", "PlasmaThrower_Tactical", "CombatShotgun_Rusty", "PipeRifle_Bayoneted",
  "GaussRifle_Hardened", "PlasmaThrower", "AlienBlaster_Focused", "SawedOffShotgun_Kneecapper",
  "Flamer_Enhanced", "Railgun_Hardened", "GaussRifle_Magnetro4000", "PipePistol_Auto",
  "SawedOffShotgun_Enhanced", "SawedOffShotgun_Rusty", "Shotgun"
] as const;

// Weapon Lists
export const WEAPON_LIST = {
  "032Pistol": '.32 Pistol',
  "Pistol": '10mm Pistol',
  "GaussRifle_Accelerated": 'Accelerated Gauss Rifle',
  "Railgun_Accelerated": 'Accelerated Railway Rifle',
  "PlasmaThrower_Agitated": 'Agitated Plasma Thrower',
  "AlienBlaster": 'Alien Blaster',
  "AmataPistol": "Amata's Pistol",
  "AlienBlaster_Amplified": 'Amplified Alien Blaster',
  "GatlingLaser_Amplified": 'Amplified Gatling Laser',
  "LaserPistol_Amplified": 'Amplified Laser Pistol',
  "LaserRifle_Amplified": 'Amplified Laser Rifle',
  "PlasmaPistol_Amplified": 'Amplified Plasma Pistol',
  "PlasmaRifle_Amplified": 'Amplified Plasma Rifle',
  "InstitutePistol_Apotheosis": 'Apotheosis',
  "032Pistol_ArmorPiercing": 'Armor Piercing .32 Pistol',
  "Pistol_ArmorPiercing": 'Armor Piercing 10mm Pistol',
  "AssaultRifle_ArmorPiercing": 'Armor Piercing Assault Rifle',
  "BBGun_ArmorPiercing": 'Armor Piercing BB Gun',
  "HuntingRifle_ArmorPiercing": 'Armor Piercing Hunting Rifle',
  "Rifle_ArmorPiercing": 'Armor Piercing Lever-Action Rifle',
  "Minigun_ArmorPiercing": 'Armor Piercing Minigun',
  "Magnum_ArmorPiercing": 'Armor Piercing Scoped .44',
  "SniperRifle_ArmorPiercing": 'Armor Piercing Sniper Rifle',
  "AssaultRifle": 'Assault Rifle',
  "PipePistol_Auto": 'Auto Pipe Pistol',
  "Melee_BaseballBat": 'Baseball Bat',
  "PipeRifle_Bayoneted": 'Bayoneted Pipe Rifle',
  "BBGun": 'BB Gun',
  "PipeRifle_BigSister": 'Big Sister',
  "Magnum_Blackhawk": 'Blackhawk',
  "PlasmaThrower_Boosted": 'Boosted Plasma Thrower',
  "Flamer_Burnmaster": 'Burnmaster',
  "Melee_ButcherKnife": 'Butcher Knife',
  "PipeRifle_Calibrated": 'Calibrated Pipe Rifle',
  "CombatShotgun_CharonsShotgun": "Charon's Shotgun",
  "CombatShotgun": 'Combat Shotgun',
  "AlienBlaster_Destabilizer": 'Destabilizer',
  "CombatShotgun_DoubleBarrelled": 'Double-Barrel Combat Shotgun',
  "SawedOffShotgun_DoubleBarrelled": 'Double-Barrel Sawed-Off Shotgun',
  "Shotgun_DoubleBarrelled": 'Double-Barrel Shotgun',
  "PlasmaThrower_DragonsMaw": "Dragon's Maw",
  "JunkJet_Electrified": 'Electrified Junk Jet',
  "032Pistol_Enhanced": 'Enhanced .32 Pistol',
  "Pistol_Enhanced": 'Enhanced 10mm Pistol',
  "AssaultRifle_Enhanced": 'Enhanced Assault Rifle',
  "BBGun_Enhanced": 'Enhanced BB Gun',
  "CombatShotgun_Enhanced": 'Enhanced Combat Shotgun',
  "Fatman_Enhanced": 'Enhanced Fat Man',
  "Flamer_Enhanced": 'Enhanced Flamer',
  "GaussRifle_Enhanced": 'Enhanced Gauss Rifle',
  "HuntingRifle_Enhanced": 'Enhanced Hunting Rifle',
  "Rifle_Enhanced": 'Enhanced Lever-Action Rifle',
  "Minigun_Enhanced": 'Enhanced Minigun',
  "MissilLauncher_Enhanced": 'Enhanced Missile Launcher',
  "Railgun_Enhanced": 'Enhanced Railway Rifle',
  "SawedOffShotgun_Enhanced": 'Enhanced Sawed-Off Shotgun',
  "Magnum_Enhanced": 'Enhanced Scoped .44',
  "Shotgun_Enhanced": 'Enhanced Shotgun',
  "SniperRifle_Enhanced": 'Enhanced Sniper Rifle',
  "InstituteRifle_Excited": 'Excited Institute Rifle',
  "Shotgun_FarmersDaughter": "Farmer's Daughter",
  "Fatman": 'Fat Man',
  "Melee_FireHydrantBat": 'Fire Hydrant Bat',
  "Fist": 'Fist',
  "Flamer": 'Flamer',
  "JunkJet_Flaming": 'Flaming Junk Jet',
  "AlienBlaster_Focused": 'Focused Alien Blaster',
  "GatlingLaser_Focused": 'Focused Gatling Laser',
  "LaserPistol_Focused": 'Focused Laser Pistol',
  "LaserRifle_Focused": 'Focused Laser Rifle',
  "PlasmaPistol_Focused": 'Focused Plasma Pistol',
  "PlasmaRifle_Focused": 'Focused Plasma Rifle',
  "GatlingLaser": 'Gatling Laser',
  "GaussRifle": 'Gauss Rifle',
  "Fatman_Guided": 'Guided Fat Man',
  "MissilLauncher_Guided": 'Guided Missile Launcher',
  "PipePistol_HairTrigger": 'Hair Trigger Pipe Pistol',
  "032Pistol_Hardened": 'Hardened .32 Pistol',
  "Pistol_Hardened": 'Hardened 10mm Pistol',
  "AssaultRifle_Hardened": 'Hardened Assault Rifle',
  "BBGun_Hardened": 'Hardened BB Gun',
  "CombatShotgun_Hardened": 'Hardened Combat Shotgun',
  "Fatman_Hardened": 'Hardened Fat Man',
  "Flamer_Hardened": 'Hardened Flamer',
  "GaussRifle_Hardened": 'Hardened Gauss Rifle',
  "HuntingRifle_Hardened": 'Hardened Hunting Rifle',
  "Rifle_Hardened": 'Hardened Lever-Action Rifle',
  "Minigun_Hardened": 'Hardened Minigun',
  "MissilLauncher_Hardened": 'Hardened Missile Launcher',
  "Railgun_Hardened": 'Hardened Railway Rifle',
  "SawedOffShotgun_Hardened": 'Hardened Sawed-Off Shotgun',
  "Magnum_Hardened": 'Hardened Scoped .44',
  "Shotgun_Hardened": 'Hardened Shotgun',
  "SniperRifle_Hardened": 'Hardened Sniper Rifle',
  "PipePistol_Heavy": 'Heavy Pipe Pistol',
  "HuntingRifle": 'Hunting Rifle',
  "InstitutePistol_Improved": 'Improved Institute Pistol',
  "InstitutePistol_Incendiary": 'Incendiary Institute Pistol',
  "AssaultRifle_Infiltrator": 'Infiltrator',
  "InstitutePistol": 'Institute Pistol',
  "InstituteRifle": 'Institute Rifle',
  "JunkJet": 'Junk Jet',
  "Melee_KitchenKnife": 'Kitchen Knife',
  "SawedOffShotgun_Kneecapper": 'Kneecapper',
  "LaserMusket": 'Laser Musket',
  "LaserPistol": 'Laser Pistol',
  "LaserRifle": 'Laser Rifle',
  "Minigun_LeadBelcher": 'Lead Belcher',
  "Rifle": 'Lever-Action Rifle',
  "Rifle_LincolnsRepeater": "Lincoln's Repeater",
  "PipePistol_LittleBrother": 'Little Brother',
  "Pistol_LoneWanderer": 'Lone Wanderer',
  "InstituteRifle_Long": 'Long Institute Rifle',
  "PipeRifle_Long": 'Long Pipe Rifle',
  "GaussRifle_Magnetro4000": 'Magnetron 4000',
  "PlasmaRifle_MeanGreenMonster": 'Mean Green Monster',
  "Minigun": 'Minigun',
  "Fatman_Mirv": 'MIRV',
  "MissilLauncher_MissLauncher": 'Miss Launcher',
  "MissilLauncher": 'Missile Launcher',
  "PlasmaPistol_MPLXNovasurge": 'MPXL Novasurge',
  "InstituteRifle_NightVision": 'Night-Vision Institute Rifle',
  "PipeRifle_NightVision": 'Night-Vision Pipe Rifle',
  "HuntingRifle_OlPainless": "Ol' Painless",
  "PlasmaThrower_Overcharged": 'Overcharged Plasma Thrower',
  "Melee_Pickaxe": 'Pickaxe',
  "PipePistol": 'Pipe Pistol',
  "PipeRifle": 'Pipe Rifle',
  "PlasmaPistol": 'Plasma Pistol',
  "PlasmaRifle": 'Plasma Rifle',
  "PlasmaThrower": 'Plasma Thrower',
  "Melee_PoolCue": 'Pool Cue',
  "Flamer_Pressurized": 'Pressurized Flamer',
  "Railgun_Railmaster": 'Railmaster',
  "Railgun": 'Railway Rifle',
  "JunkJet_RecoilCompensated": 'Recoil Compensated Junk Jet',
  "BBGun_RedRocket": 'Red Rocket',
  "Melee_RaiderSword": 'Relentless Raider Sword',
  "032Pistol_Rusty": 'Rusty .32 Pistol',
  "Pistol_Rusty": 'Rusty 10mm Pistol',
  "AlienBlaster_Rusty": 'Rusty Alien Blaster',
  "AssaultRifle_Rusty": 'Rusty Assault Rifle',
  "BBGun_Rusty": 'Rusty BB Gun',
  "CombatShotgun_Rusty": 'Rusty Combat Shotgun',
  "Fatman_Rusty": 'Rusty Fat Man',
  "Flamer_Rusty": 'Rusty Flamer',
  "GatlingLaser_Rusty": 'Rusty Gatling Laser',
  "GaussRifle_Rusty": 'Rusty Gauss Rifle',
  "HuntingRifle_Rusty": 'Rusty Hunting Rifle',
  "LaserPistol_Rusty": 'Rusty Laser Pistol',
  "LaserRifle_Rusty": 'Rusty Laser Rifle',
  "Rifle_Rusty": 'Rusty Lever-Action Rifle',
  "Minigun_Rusty": 'Rusty Minigun',
  "MissilLauncher_Rusty": 'Rusty Missile Launcher',
  "PlasmaPistol_Rusty": 'Rusty Plasma Pistol',
  "PlasmaRifle_Rusty": 'Rusty Plasma Rifle',
  "Railgun_Rusty": 'Rusty Railway Rifle',
  "SawedOffShotgun_Rusty": 'Rusty Sawed-Off Shotgun',
  "Magnum_Rusty": 'Rusty Scoped .44',
  "Shotgun_Rusty": 'Rusty Shotgun',
  "SniperRifle_Rusty": 'Rusty Sniper Rifle',
  "SawedOffShotgun": 'Sawed-Off Shotgun',
  "InstitutePistol_Scattered": 'Scattered Institute Pistol',
  "Magnum": 'Scoped .44',
  "InstitutePistol_Scoped": 'Scoped Institute Pistol',
  "PipePistol_Scoped": 'Scoped Pipe Pistol',
  "Shotgun": 'Shotgun',
  "LaserPistol_SmugglersEnd": "Smuggler's End",
  "SniperRifle": 'Sniper Rifle',
  "JunkJet_Tactical": 'Tactical Junk Jet',
  "PlasmaThrower_Tactical": 'Tactical Plasma Thrower',
  "InstituteRifle_Targeting": 'Targeting Institute Rifle',
  "JunkJet_TechniciansRevenge": "Technician's Revenge",
  "AlienBlaster_Tuned": 'Tuned Alien Blaster',
  "GatlingLaser_Tuned": 'Tuned Gatling Laser',
  "LaserPistol_Tuned": 'Tuned Laser Pistol',
  "LaserRifle_Tuned": 'Tuned Laser Rifle',
  "PlasmaPistol_Tuned": 'Tuned Plasma Pistol',
  "PlasmaRifle_Tuned": 'Tuned Plasma Rifle',
  "GatlingLaser_Vengeance": 'Vengeance',
  "SniperRifle_VictoryRifle": 'Victory Rifle',
  "InstituteRifle_VirgilsRifle": "Virgil's Rifle",
  "LaserRifle_WaserWifle": 'Wazer Wifle',
  "032Pistol_WildBillsSidearm": "Wild Bill's Sidearm"
} as const;

// Outfit Lists
export const OUTFIT_LIST = {
  "AbrahamSpecial": "Abraham's Relaxedwear",
  "AlistairSpecial": "Tenpenny's Suit",
  "AllNightware": 'Nightwear',
  "AllNightware_Lucky": 'Lucky Nightwear',
  "AllNightware_Naughty": 'Naughty Nightwear',
  "AmataSpecial": "Amata's Jumpsuit",
  "ArgyleSweater": 'Accountant Outfit',
  "BaseballUniform": 'Baseball Uniform',
  "BattleArmor": 'Battle Armor',
  "BattleArmor_Heavy": 'Heavy Battle Armor',
  "BattleArmor_Sturdy": 'Sturdy Battle Armor',
  "BishopSpecial": 'Clergy Outfit',
  "BittercupSpecial": "Bittercup's Outfit",
  "BOSUniform": 'BoS Uniform',
  "BOSUniform_Advanced": 'Advanced BoS Uniform',
  "BOSUniform_Expert": 'Expert BoS Uniform',
  "BowlingShirt": 'Drag Racer',
  "BusinessDress": 'Agent Provocateur',
  "BusinessSuit": 'Business Suit',
  "ButchSpecial": "Tunnel Snakes' Outfit",
  "CheckeredShirt": 'Spring Casualwear',
  "ColonelSpecial": "Autumn's Uniform",
  "CombatArmor": 'Combat Armor',
  "CombatArmor_Heavy": 'Heavy Combat Armor',
  "CombatArmor_Sturdy": 'Sturdy Combat Armor',
  "ComedianSpecial": 'Comedian Outfit',
  "CromwellSpecial": "Confessor Cromwell's Rags",
  "Detective": 'Detective Outfit',
  "DooWopOutfit": 'Doo-Wop Singer',
  "DrLiSpecial": "Doctor Li's Outfit",
  "ElderLyonsSpecial": "Elder Lyon's Robe",
  "EmpressSpecial": 'Republic Robes',
  "EngineerSpecial": 'Engineer Outfit',
  "EulogyJonesSpecial": "Eulogy Jones' Suit",
  "FarHarborSpecial": 'Tattered Longcoat',
  "FlightSuit": 'Flight Suit',
  "FlightSuit_Advanced": 'Advanced Flight Suit',
  "FlightSuit_Expert": 'Expert Flight Suit',
  "FormalWear": 'Formal Wear',
  "FormalWear_Fancy": 'Fancy Formal Wear',
  "FormalWear_Lucky": 'Lucky Formal Wear',
  "GreaserSpecial": 'Greaser Outfit',
  "HandymanJumpsuit": 'Handyman Jumpsuit',
  "HandymanJumpsuit_Advanced": 'Advanced Jumpsuit',
  "HandymanJumpsuit_Expert": 'Expert Jumpsuit',
  "HarknessSpecial": "Harkness' Security Uniform",
  "HazmatSuit": 'Wasteland Gear',
  "HazmatSuit_Heavy": 'Heavy Wasteland Gear',
  "HazmatSuit_Sturdy": 'Sturdy Wasteland Gear',
  "HunterGear_Bounty": 'Bounty Hunter Gear',
  "HunterGear_Mutant": 'Mutant Hunter Gear',
  "HunterGear_Treasure": 'Treasure Hunter Gear',
  "InstituteJumper_Advanced": 'Advanced Institute Jumper',
  "InstituteJumper_Expert": 'Expert Institute Jumper',
  "JacketTshirt": 'Motorcycle Jacket',
  "JamesSpecial": "Dad's Lab Uniform",
  "JerichoSpecial": "Jericho's Leather Armor",
  "JobinsonsJersey": "Rackie Jobinson's Jersey",
  "jumpsuit": 'Vault Suit',
  "KingSpecial": 'Medieval Ruler Outfit',
  "KnightSpecial": 'Knight Armor',
  "LabCoat": 'Lab Coat',
  "LabCoat_Advanced": 'Advanced Lab Coat',
  "LabCoat_Expert": 'Expert Lab Coat',
  "LibrarianSpecial": 'Librarian Outfit',
  "LifeguardOutfit": 'Lifeguard Outfit',
  "LoungeShirt": 'Bowling Shirt',
  "LucasSpecial": "Sheriff's Duster",
  "MayorSpecial": 'Mayor Outfit',
  "MechanicJumpsuit": 'Mechanic Jumpsuit',
  "MetalArmor_Heavy": 'Heavy Metal Armor',
  "MetalArmor_Sturdy": 'Sturdy Metal Armor',
  "MilitaryJumpsuit": 'Military Fatigues',
  "MilitaryJumpsuit_Commander": 'Commander Fatigues',
  "MilitaryJumpsuit_Officer": 'Officer Fatigues',
  "MoiraSpecial": "Moira's RobCo Jumpsuit",
  "MoviefanSpecial": 'Movie Fan Outfit',
  "MrBurkeSpecial": 'Mr Burke Special',
  "NinjaSuit": 'Ninja Outfit',
  "PiperSpecial": "Piper's Outfit",
  "PolkaDotDress": 'Polka Dot Sundress',
  "PowerArmor": 'T-45a Power Armor',
  "PowerArmor_51a": 'T-51a Power Armor',
  "PowerArmor_51d": 'T-51d Power Armor',
  "PowerArmor_51f": 'T-51f Power Armor',
  "PowerArmor_MkI": 'X-01 Mk I Power Armor',
  "PowerArmor_MkIV": 'X-01 Mk IV Power Armor',
  "PowerArmor_MkVI": 'X-01 Mk VI Power Armor',
  "PowerArmor_T45d": 'T-45d Power Armor',
  "PowerArmor_T45f": 'T-45f Power Armor',
  "PowerArmor_T60a": 'T-60a Power Armor',
  "PowerArmor_T60d": 'T-60d Power Armor',
  "PowerArmor_T60f": 'T-60f Power Armor',
  "PrestonSpecial": 'Minuteman Uniform',
  "PrinceSpecial": 'Nobility Outfit',
  "ProfessorSpecial": 'Professor Outfit',
  "RadiationSuit": 'Radiation Suit',
  "RadiationSuit_Advanced": 'Advanced Radiation Suit',
  "RadiationSuit_Expert": 'Expert Radiation Suit',
  "RaiderArmor": 'Raider Armor',
  "RaiderArmor_Heavy": 'Heavy Raider Armor',
  "RaiderArmor_Sturdy": 'Sturdy Raider Armor',
  "RiotGear": 'Merc Gear',
  "RiotGear_Heavy": 'Heavy Merc Gear',
  "RiotGear_Sturdy": 'Sturdy Merc Gear',
  "RothchildSpecial": "Scribe Rothchild's Robe",
  "SantaSuit_Original": 'Original Santa Suit',
  "SarahSpecial": "Lyon's Pride Armor",
  "ScientistScrubs": 'Junior Officer Uniform',
  "ScientistScrubs_Commander": 'Commander Uniform',
  "ScientistScrubs_Officer": 'Officer Uniform',
  "ScifiSpecial": 'Sci-Fi Fan Outfit',
  "ScribeRobe": 'Scribe Robe',
  "ScribeRobe_Elder": 'Elder Robe',
  "ScribeRobe_Initiate": 'Initiate Robe',
  "SequinDress": 'Vault Socialite',
  "SlasherSpecial": 'Horror Fan Outfit',
  "SodaFountainDress": 'Soda Fountain Dress',
  "SoldierSpecial": 'Soldier Uniform',
  "SpecialThemeHalloween": 'Ghost Costume',
  "SpecialThemeHalloween2": 'Skeleton Costume',
  "SpecialThemeThanksGiving": 'Pilgrim Outfit',
  "SpecialThemeXmas": 'Santa Suit',
  "SpecialThemeXmas2": 'Elf Outfit',
  "SportsfanSpecial": 'Sports Fan Outfit',
  "StarPaladinSpecial": "Cross' Power Armor",
  "SurgeonSpecial": 'Surgeon Outfit',
  "SurvivorSpecial": 'Survivor Armor',
  "Suspenders": 'Bespoke Attire',
  "SweaterVest": 'Pre-War Suburbanite',
  "Swimsuit": 'Swimsuit',
  "SwingDress": 'Swing Dress',
  "SynthArmor_Heavy": 'Heavy Synth Armor',
  "ThreedogSpecial": "Three Dog's Outfit",
  "TiedBlouse": 'Country Girl',
  "UtilityJumpsuit": 'Armored Vault Suit',
  "UtilityJumpsuit_Heavy": 'Heavy Vault Suit',
  "UtilityJumpsuit_Sturdy": 'Sturdy Vault Suit',
  "Vest": 'Post-War Casanova',
  "WaitressUniform": 'Waitress Uniform',
  "WandererArmor": 'Leather Armor',
  "WandererArmor_Heavy": 'Heavy Leather Armor',
  "WandererArmor_Sturdy": 'Sturdy Leather Armor',
  "WastelandSurgeon": 'Wasteland Surgeon',
  "WastelandSurgeon_Doctor": 'Wasteland Doctor',
  "WastelandSurgeon_Settler": 'Wasteland Medic',
  "WorkDress": 'Rural Schoolmarm',
  "WrestlerSpecial": 'Wrestler Outfit'
} as const;
