export const OUTFIT_LIST = {
  "AbrahamSpecial": "Abraham's Relaxedwear",
  "AlistairSpecial": "Tenpenny's Suit",
  "AllNightware": 'Nightwear',
  "AllNightware_Lucky": 'Lucky Nightwear',
  "AllNightware_Naughty": 'Naughty Nightwear',
  "AmataSpecial": "Amata's Jumpsuit",
  "ArgyleSweater": 'Accountant Outfit',
  "BaseballUniform": 'Baseball Uniform',
  "BattleArmor": 'Battle Armor',
  "BattleArmor_Heavy": 'Heavy Battle Armor',
  "BattleArmor_Sturdy": 'Sturdy Battle Armor',
  "BishopSpecial": 'Clergy Outfit',
  "BittercupSpecial": "Bittercup's Outfit",
  "BOSUniform": 'BoS Uniform',
  "BOSUniform_Advanced": 'Advanced BoS Uniform',
  "BOSUniform_Expert": 'Expert BoS Uniform',
  "BowlingShirt": 'Drag Racer',
  "BusinessDress": 'Agent Provocateur',
  "BusinessSuit": 'Business Suit',
  "ButchSpecial": "Tunnel Snakes' Outfit",
  "CheckeredShirt": 'Spring Casualwear',
  "ColonelSpecial": "Autumn's Uniform",
  "CombatArmor": 'Combat Armor',
  "CombatArmor_Heavy": 'Heavy Combat Armor',
  "CombatArmor_Sturdy": 'Sturdy Combat Armor',
  "ComedianSpecial": 'Comedian Outfit',
  "CromwellSpecial": "Confessor Cromwell's Rags",
  "Detective": 'Detective Outfit',
  "DooWopOutfit": 'Doo-Wop Singer',
  "DrLiSpecial": "Doctor Li's Outfit",
  "ElderLyonsSpecial": "Elder Lyon's Robe",
  "EmpressSpecial": 'Republic Robes',
  "EngineerSpecial": 'Engineer Outfit',
  "EulogyJonesSpecial": "Eulogy Jones' Suit",
  "FarHarborSpecial": 'Tattered Longcoat',
  "FlightSuit": 'Flight Suit',
  "FlightSuit_Advanced": 'Advanced Flight Suit',
  "FlightSuit_Expert": 'Expert Flight Suit',
  "FormalWear": 'Formal Wear',
  "FormalWear_Fancy": 'Fancy Formal Wear',
  "FormalWear_Lucky": 'Lucky Formal Wear',
  "GreaserSpecial": 'Greaser Outfit',
  "HandymanJumpsuit": 'Handyman Jumpsuit',
  "HandymanJumpsuit_Advanced": 'Advanced Jumpsuit',
  "HandymanJumpsuit_Expert": 'Expert Jumpsuit',
  "HarknessSpecial": "Harkness' Security Uniform",
  "HazmatSuit": 'Wasteland Gear',
  "HazmatSuit_Heavy": 'Heavy Wasteland Gear',
  "HazmatSuit_Sturdy": 'Sturdy Wasteland Gear',
  "HunterGear_Bounty": 'Bounty Hunter Gear',
  "HunterGear_Mutant": 'Mutant Hunter Gear',
  "HunterGear_Treasure": 'Treasure Hunter Gear',
  "InstituteJumper_Advanced": 'Advanced Institute Jumper',
  "InstituteJumper_Expert": 'Expert Institute Jumper',
  "JacketTshirt": 'Motorcycle Jacket',
  "JamesSpecial": "Dad's Lab Uniform",
  "JerichoSpecial": "Jericho's Leather Armor",
  "JobinsonsJersey": "Rackie Jobinson's Jersey",
  "jumpsuit": 'Vault Suit',
  "KingSpecial": 'Medieval Ruler Outfit',
  "KnightSpecial": 'Knight Armor',
  "LabCoat": 'Lab Coat',
  "LabCoat_Advanced": 'Advanced Lab Coat',
  "LabCoat_Expert": 'Expert Lab Coat',
  "LibrarianSpecial": 'Librarian Outfit',
  "LifeguardOutfit": 'Lifeguard Outfit',
  "LoungeShirt": 'Bowling Shirt',
  "LucasSpecial": "Sheriff's Duster",
  "MayorSpecial": 'Mayor Outfit',
  "MechanicJumpsuit": 'Mechanic Jumpsuit',
  "MetalArmor_Heavy": 'Heavy Metal Armor',
  "MetalArmor_Sturdy": 'Sturdy Metal Armor',
  "MilitaryJumpsuit": 'Military Fatigues',
  "MilitaryJumpsuit_Commander": 'Commander Fatigues',
  "MilitaryJumpsuit_Officer": 'Officer Fatigues',
  "MoiraSpecial": "Moira's RobCo Jumpsuit",
  "MoviefanSpecial": 'Movie Fan Outfit',
  "MrBurkeSpecial": 'Mr Burke Special',
  "NinjaSuit": 'Ninja Outfit',
  "PiperSpecial": "Piper's Outfit",
  "PolkaDotDress": 'Polka Dot Sundress',
  "PowerArmor": 'T-45a Power Armor',
  "PowerArmor_51a": 'T-51a Power Armor',
  "PowerArmor_51d": 'T-51d Power Armor',
  "PowerArmor_51f": 'T-51f Power Armor',
  "PowerArmor_MkI": 'X-01 Mk I Power Armor',
  "PowerArmor_MkIV": 'X-01 Mk IV Power Armor',
  "PowerArmor_MkVI": 'X-01 Mk VI Power Armor',
  "PowerArmor_T45d": 'T-45d Power Armor',
  "PowerArmor_T45f": 'T-45f Power Armor',
  "PowerArmor_T60a": 'T-60a Power Armor',
  "PowerArmor_T60d": 'T-60d Power Armor',
  "PowerArmor_T60f": 'T-60f Power Armor',
  "PrestonSpecial": 'Minuteman Uniform',
  "PrinceSpecial": 'Nobility Outfit',
  "ProfessorSpecial": 'Professor Outfit',
  "RadiationSuit": 'Radiation Suit',
  "RadiationSuit_Advanced": 'Advanced Radiation Suit',
  "RadiationSuit_Expert": 'Expert Radiation Suit',
  "RaiderArmor": 'Raider Armor',
  "RaiderArmor_Heavy": 'Heavy Raider Armor',
  "RaiderArmor_Sturdy": 'Sturdy Raider Armor',
  "RiotGear": 'Merc Gear',
  "RiotGear_Heavy": 'Heavy Merc Gear',
  "RiotGear_Sturdy": 'Sturdy Merc Gear',
  "RothchildSpecial": "Scribe Rothchild's Robe",
  "SantaSuit_Original": 'Original Santa Suit',
  "SarahSpecial": "Lyon's Pride Armor",
  "ScientistScrubs": 'Junior Officer Uniform',
  "ScientistScrubs_Commander": 'Commander Uniform',
  "ScientistScrubs_Officer": 'Officer Uniform',
  "ScifiSpecial": 'Sci-Fi Fan Outfit',
  "ScribeRobe": 'Scribe Robe',
  "ScribeRobe_Elder": 'Elder Robe',
  "ScribeRobe_Initiate": 'Initiate Robe',
  "SequinDress": 'Vault Socialite',
  "SlasherSpecial": 'Horror Fan Outfit',
  "SodaFountainDress": 'Soda Fountain Dress',
  "SoldierSpecial": 'Soldier Uniform',
  "SpecialThemeHalloween": 'Ghost Costume',
  "SpecialThemeHalloween2": 'Skeleton Costume',
  "SpecialThemeThanksGiving": 'Pilgrim Outfit',
  "SpecialThemeXmas": 'Santa Suit',
  "SpecialThemeXmas2": 'Elf Outfit',
  "SportsfanSpecial": 'Sports Fan Outfit',
  "StarPaladinSpecial": "Cross' Power Armor",
  "SurgeonSpecial": 'Surgeon Outfit',
  "SurvivorSpecial": 'Survivor Armor',
  "Suspenders": 'Bespoke Attire',
  "SweaterVest": 'Pre-War Suburbanite',
  "Swimsuit": 'Swimsuit',
  "SwingDress": 'Swing Dress',
  "SynthArmor_Heavy": 'Heavy Synth Armor',
  "ThreedogSpecial": "Three Dog's Outfit",
  "TiedBlouse": 'Country Girl',
  "UtilityJumpsuit": 'Armored Vault Suit',
  "UtilityJumpsuit_Heavy": 'Heavy Vault Suit',
  "UtilityJumpsuit_Sturdy": 'Sturdy Vault Suit',
  "Vest": 'Post-War Casanova',
  "WaitressUniform": 'Waitress Uniform',
  "WandererArmor": 'Leather Armor',
  "WandererArmor_Heavy": 'Heavy Leather Armor',
  "WandererArmor_Sturdy": 'Sturdy Leather Armor',
  "WastelandSurgeon": 'Wasteland Surgeon',
  "WastelandSurgeon_Doctor": 'Wasteland Doctor',
  "WastelandSurgeon_Settler": 'Wasteland Medic',
  "WorkDress": 'Rural Schoolmarm',
  "WrestlerSpecial": 'Wrestler Outfit'

  "EnclaveSecurityOutfit": "Enclave Security Outfit",
  "HanksPowerArmor": "Hank's Power Armor",
  "Incognito": "Incognito",
  "MaJuneJacket": "Ma June Jacket",
  "MojaveWastelandSurvivor": "Mojave Wasteland Survivor",
  "MoldaversArmor": "Moldaver's Armor",
  "RobCoRdSuit": "RobCo R&D Suit",
  "Vault33Suit": "Vault 33 Suit",
  "WilzigsTravelwear": "Wilzig's Travelwear",
} as const;