export const OUTFIT_LIST = {
  "AbrahamSpecial": "Abraham's Relaxedwear",
  "AlistairSpecial": "Tenpenny's Suit",
  "AllNightware": 'Nightwear',
  "AllNightware_Lucky": 'Lucky Nightwear',
  "AllNightware_Naughty": 'Naughty Nightwear',
  "AmataSpecial": "Amata's Jumpsuit",
  "ArgyleSweater": 'Accountant Outfit',
  "BaseballUniform": 'Baseball Uniform',
  "BattleArmor": 'Battle Armor',
  "BattleArmor_Heavy": 'Heavy Battle Armor',
  "BattleArmor_Sturdy": 'Sturdy Battle Armor',
  "BishopSpecial": 'Clergy Outfit',
  "BittercupSpecial": "Bittercup's Outfit",
  "BOSUniform": 'BoS Uniform',
  "BOSUniform_Advanced": 'Advanced BoS Uniform',
  "BOSUniform_Expert": 'Expert BoS Uniform',
  "BowlingShirt": 'Drag Racer',
  "BusinessDress": 'Agent Provocateur',
  "BusinessSuit": 'Business Suit',
  "ButchSpecial": "Tunnel Snakes' Outfit",
  "CheckeredShirt": 'Spring Casualwear',
  "ColonelSpecial": "Autumn's Uniform",
  "CombatArmor": 'Combat Armor',
  "CombatArmor_Heavy": 'Heavy Combat Armor',
  "CombatArmor_Sturdy": 'Sturdy Combat Armor',
  "ComedianSpecial": 'Comedian Outfit',
  "CromwellSpecial": "Confessor Cromwell's Rags",
  "Detective": 'Detective Outfit',
  "DooWopOutfit": 'Doo-Wop Singer',
  "DrLiSpecial": "Doctor Li's Outfit",
  "ElderLyonsSpecial": "Elder Lyon's Robe",
  "EmpressSpecial": 'Republic Robes',
  "EngineerSpecial": 'Engineer Outfit',
  "EulogyJonesSpecial": "Eulogy Jones' Suit",
  "FarHarborSpecial": 'Tattered Longcoat',
  "FlightSuit": 'Flight Suit',
  "FlightSuit_Advanced": 'Advanced Flight Suit',
  "FlightSuit_Expert": 'Expert Flight Suit',
  "FormalWear": 'Formal Wear',
  "FormalWear_Fancy": 'Fancy Formal Wear',
  "FormalWear_Lucky": 'Lucky Formal Wear',
  "GreaserSpecial": 'Greaser Outfit',
  "HandymanJumpsuit": 'Handyman Jumpsuit',
  "HandymanJumpsuit_Advanced": 'Advanced Jumpsuit',
  "HandymanJumpsuit_Expert": 'Expert Jumpsuit',
  "HarknessSpecial": "Harkness' Security Uniform",
  "HazmatSuit": 'Wasteland Gear',
  "HazmatSuit_Heavy": 'Heavy Wasteland Gear',
  "HazmatSuit_Sturdy": 'Sturdy Wasteland Gear',
  "HunterGear_Bounty": 'Bounty Hunter Gear',
  "HunterGear_Mutant": 'Mutant Hunter Gear',
  "HunterGear_Treasure": 'Treasure Hunter Gear',
  "InstituteJumper_Advanced": 'Advanced Institute Jumper',
  "InstituteJumper_Expert": 'Expert Institute Jumper',
  "JacketTshirt": 'Motorcycle Jacket',
  "JamesSpecial": "Dad's Lab Uniform",
  "JerichoSpecial": "Jericho's Leather Armor",
  "JobinsonsJersey": "Rackie Jobinson's Jersey",
  "jumpsuit": 'Vault Suit',
  "KingSpecial": 'Medieval Ruler Outfit',
  "KnightSpecial": 'Knight Armor',
  "LabCoat": 'Lab Coat',
  "LabCoat_Advanced": 'Advanced Lab Coat',
  "LabCoat_Expert": 'Expert Lab Coat',
  "LibrarianSpecial": 'Librarian Outfit',
  "LifeguardOutfit": 'Lifeguard Outfit',
  "LoungeShirt": 'Bowling Shirt',
  "LucasSpecial": "Sheriff's Duster",
  "MayorSpecial": 'Mayor Outfit',
  "MechanicJumpsuit": 'Mechanic Jumpsuit',
  "MetalArmor_Heavy": 'Heavy Metal Armor',
  "MetalArmor_Sturdy": 'Sturdy Metal Armor',
  "MilitaryJumpsuit": 'Military Fatigues',
  "MilitaryJumpsuit_Commander": 'Commander Fatigues',
  "MilitaryJumpsuit_Officer": 'Officer Fatigues',
  "MoiraSpecial": "Moira's RobCo Jumpsuit",
  "MoviefanSpecial": 'Movie Fan Outfit',
  "MrBurkeSpecial": 'Mr Burke Special',
  "NinjaSuit": 'Ninja Outfit',
  "PiperSpecial": "Piper's Outfit",
  "PolkaDotDress": 'Polka Dot Sundress',
  "PowerArmor": 'T-45a Power Armor',
  "PowerArmor_51a": 'T-51a Power Armor',
  "PowerArmor_51d": 'T-51d Power Armor',
  "PowerArmor_51f": 'T-51f Power Armor',
  "PowerArmor_MkI": 'X-01 Mk I Power Armor',
  "PowerArmor_MkIV": 'X-01 Mk IV Power Armor',
  "PowerArmor_MkVI": 'X-01 Mk VI Power Armor',
  "PowerArmor_T45d": 'T-45d Power Armor',
  "PowerArmor_T45f": 'T-45f Power Armor',
  "PowerArmor_T60a": 'T-60a Power Armor',
  "PowerArmor_T60d": 'T-60d Power Armor',
  "PowerArmor_T60f": 'T-60f Power Armor',
  "PrestonSpecial": 'Minuteman Uniform',
  "PrinceSpecial": 'Nobility Outfit',
  "ProfessorSpecial": 'Professor Outfit',
  "RadiationSuit": 'Radiation Suit',
  "RadiationSuit_Advanced": 'Advanced Radiation Suit',
  "RadiationSuit_Expert": 'Expert Radiation Suit',
  "RaiderArmor": 'Raider Armor',
  "RaiderArmor_Heavy": 'Heavy Raider Armor',
  "RaiderArmor_Sturdy": 'Sturdy Raider Armor',
  "RiotGear": 'Merc Gear',
  "RiotGear_Heavy": 'Heavy Merc Gear',
  "RiotGear_Sturdy": 'Sturdy Merc Gear',
  "RothchildSpecial": "Scribe Rothchild's Robe",
  "SantaSuit_Original": 'Original Santa Suit',
  "SarahSpecial": "Lyon's Pride Armor",
  "ScientistScrubs": 'Junior Officer Uniform',
  "ScientistScrubs_Commander": 'Commander Uniform',
  "ScientistScrubs_Officer": 'Officer Uniform',
  "ScifiSpecial": 'Sci-Fi Fan Outfit',
  "ScribeRobe": 'Scribe Robe',
  "ScribeRobe_Elder": 'Elder Robe',
  "ScribeRobe_Initiate": 'Initiate Robe',
  "SequinDress": 'Vault Socialite',
  "SlasherSpecial": 'Horror Fan Outfit',
  "SodaFountainDress": 'Soda Fountain Dress',
  "SoldierSpecial": 'Soldier Uniform',
  "SpecialThemeHalloween": 'Ghost Costume',
  "SpecialThemeHalloween2": 'Skeleton Costume',
  "SpecialThemeThanksGiving": 'Pilgrim Outfit',
  "SpecialThemeXmas": 'Santa Suit',
  "SpecialThemeXmas2": 'Elf Outfit',
  "SportsfanSpecial": 'Sports Fan Outfit',
  "StarPaladinSpecial": "Cross' Power Armor",
  "SurgeonSpecial": 'Surgeon Outfit',
  "SurvivorSpecial": 'Survivor Armor',
  "Suspenders": 'Bespoke Attire',
  "SweaterVest": 'Pre-War Suburbanite',
  "Swimsuit": 'Swimsuit',
  "SwingDress": 'Swing Dress',
  "SynthArmor_Heavy": 'Heavy Synth Armor',
  "ThreedogSpecial": "Three Dog's Outfit",
  "TiedBlouse": 'Country Girl',
  "UtilityJumpsuit": 'Armored Vault Suit',
  "UtilityJumpsuit_Heavy": 'Heavy Vault Suit',
  "UtilityJumpsuit_Sturdy": 'Sturdy Vault Suit',
  "Vest": 'Post-War Casanova',
  "WaitressUniform": 'Waitress Uniform',
  "WandererArmor": 'Leather Armor',
  "WandererArmor_Heavy": 'Heavy Leather Armor',
  "WandererArmor_Sturdy": 'Sturdy Leather Armor',
  "WastelandSurgeon": 'Wasteland Surgeon',
  "WastelandSurgeon_Doctor": 'Wasteland Doctor',
  "WastelandSurgeon_Settler": 'Wasteland Medic',
  "WorkDress": 'Rural Schoolmarm',
  "WrestlerSpecial": 'Wrestler Outfit',

  "EnclaveSecurityOutfit": "Enclave Security Outfit",
  "HanksPowerArmor": "Hank's Power Armor",
  "Incognito": "Incognito",
  "MaJuneJacket": "Ma June Jacket",
  "MojaveWastelandSurvivor": "Mojave Wasteland Survivor",
  "MoldaversArmor": "Moldaver's Armor",
  "RobCoRdSuit": "RobCo R&D Suit",
  "Vault33Suit": "Vault 33 Suit",
  "WilzigsTravelwear": "Wilzig's Travelwear",
} as const;

export const OUTFIT_SPECIAL_BONUSES = {
  "AbrahamSpecial": { S: 0, P: 0, E: 1, C: 0, I: 2, A: 2, L: 2 },
  "AlistairSpecial": { S: 0, P: 2, E: 0, C: 2, I: 2, A: 0, L: 1 },
  "AllNightware": { S: 0, P: 0, E: 0, C: 3, I: 0, A: 0, L: 0 },
  "AllNightware_Lucky": { S: 0, P: 0, E: 0, C: 7, I: 0, A: 0, L: 0 },
  "AllNightware_Naughty": { S: 0, P: 0, E: 0, C: 5, I: 0, A: 0, L: 0 },
  "AmataSpecial": { S: 0, P: 0, E: 0, C: 0, I: 0, A: 0, L: 0 },
  "ArgyleSweater": { S: 0, P: 4, E: 0, C: 0, I: 0, A: 0, L: 0 },
  "BOSUniform": { S: 0, P: 2, E: 0, C: 1, I: 0, A: 0, L: 0 },
  "BOSUniform_Advanced": { S: 0, P: 3, E: 0, C: 2, I: 0, A: 0, L: 0 },
  "BOSUniform_Expert": { S: 0, P: 4, E: 0, C: 3, I: 0, A: 0, L: 0 },
  "BaseballUniform": { S: 0, P: 0, E: 0, C: 0, I: 0, A: 4, L: 1 },
  "BattleArmor": { S: 2, P: 0, E: 1, C: 0, I: 0, A: 0, L: 0 },
  "BattleArmor_Heavy": { S: 4, P: 0, E: 3, C: 0, I: 0, A: 0, L: 0 },
  "BattleArmor_Sturdy": { S: 3, P: 0, E: 2, C: 0, I: 0, A: 0, L: 0 },
  "BishopSpecial": { S: 0, P: 0, E: 0, C: 4, I: 0, A: 0, L: 1 },
  "BittercupSpecial": { S: 2, P: 2, E: 2, C: 1, I: 0, A: 0, L: 0 },
  "BowlingShirt": { S: 1, P: 0, E: 1, C: 0, I: 0, A: 1, L: 1 },
  "BusinessDress": { S: 0, P: 0, E: 0, C: 0, I: 4, A: 0, L: 0 },
  "BusinessSuit": { S: 0, P: 0, E: 0, C: 4, I: 0, A: 0, L: 0 },
  "ButchSpecial": { S: 0, P: 2, E: 1, C: 2, I: 0, A: 2, L: 0 },
  "CheckeredShirt": { S: 0, P: 0, E: 1, C: 0, I: 0, A: 1, L: 0 },
  "ColonelSpecial": { S: 2, P: 2, E: 2, C: 1, I: 0, A: 0, L: 0 },
  "CombatArmor": { S: 2, P: 0, E: 0, C: 0, I: 0, A: 1, L: 0 },
  "CombatArmor_Heavy": { S: 4, P: 0, E: 0, C: 0, I: 0, A: 3, L: 0 },
  "CombatArmor_Sturdy": { S: 3, P: 0, E: 0, C: 0, I: 0, A: 2, L: 0 },
  "ComedianSpecial": { S: 0, P: 2, E: 0, C: 2, I: 0, A: 0, L: 1 },
  "CromwellSpecial": { S: 0, P: 2, E: 2, C: 0, I: 1, A: 0, L: 2 },
  "Detective": { S: 0, P: 4, E: 4, C: 0, I: 4, A: 0, L: 4 },
  "DooWopOutfit": { S: 1, P: 0, E: 0, C: 1, I: 0, A: 1, L: 1 },
  "DrLiSpecial": { S: 0, P: 0, E: 0, C: 0, I: 0, A: 0, L: 0 },
  "ElderLyonsSpecial": { S: 0, P: 0, E: 0, C: 0, I: 0, A: 0, L: 0 },
  "EmpressSpecial": { S: 0, P: 0, E: 0, C: 4, I: 0, A: 0, L: 1 },
  "EnclaveSecurityOutfit": { S: 2, P: 0, E: 2, C: 0, I: 0, A: 0, L: 0 },
  "EngineerSpecial": { S: 0, P: 0, E: 2, C: 0, I: 2, A: 0, L: 1 },
  "EulogyJonesSpecial": { S: 0, P: 2, E: 0, C: 2, I: 1, A: 0, L: 2 },
  "FarHarborSpecial": { S: 2, P: 0, E: 2, C: 2, I: 0, A: 0, L: 2 },
  "FlightSuit": { S: 0, P: 0, E: 1, C: 0, I: 0, A: 2, L: 0 },
  "FlightSuit_Advanced": { S: 0, P: 0, E: 2, C: 0, I: 0, A: 3, L: 0 },
  "FlightSuit_Expert": { S: 0, P: 0, E: 3, C: 0, I: 0, A: 4, L: 0 },
  "FormalWear": { S: 0, P: 0, E: 0, C: 0, I: 0, A: 0, L: 3 },
  "FormalWear_Fancy": { S: 0, P: 0, E: 0, C: 0, I: 0, A: 0, L: 5 },
  "FormalWear_Lucky": { S: 0, P: 0, E: 0, C: 0, I: 0, A: 0, L: 7 },
  "GreaserSpecial": { S: 0, P: 0, E: 0, C: 2, I: 0, A: 2, L: 1 },
  "HandymanJumpsuit": { S: 0, P: 0, E: 0, C: 0, I: 0, A: 3, L: 0 },
  "HandymanJumpsuit_Advanced": { S: 0, P: 0, E: 0, C: 0, I: 0, A: 5, L: 0 },
  "HandymanJumpsuit_Expert": { S: 0, P: 0, E: 0, C: 0, I: 0, A: 7, L: 0 },
  "HanksPowerArmor": { S: 2, P: 0, E: 3, C: 2, I: 0, A: 0, L: 0 },
  "HarknessSpecial": { S: 0, P: 0, E: 0, C: 0, I: 0, A: 0, L: 0 },
  "HazmatSuit": { S: 0, P: 0, E: 3, C: 0, I: 0, A: 0, L: 0 },
  "HazmatSuit_Heavy": { S: 0, P: 0, E: 7, C: 0, I: 0, A: 0, L: 0 },
  "HazmatSuit_Sturdy": { S: 0, P: 0, E: 5, C: 0, I: 0, A: 0, L: 0 },
  "HunterGear_Bounty": { S: 3, P: 2, E: 0, C: 0, I: 0, A: 0, L: 0 },
  "HunterGear_Mutant": { S: 4, P: 3, E: 0, C: 0, I: 0, A: 0, L: 0 },
  "HunterGear_Treasure": { S: 2, P: 1, E: 0, C: 0, I: 0, A: 0, L: 0 },
  "Incognito": { S: 0, P: 0, E: 0, C: 0, I: 0, A: 0, L: 0 },
  "InstituteJumper_Advanced": { S: 0, P: 0, E: 0, C: 0, I: 3, A: 2, L: 0 },
  "InstituteJumper_Expert": { S: 0, P: 0, E: 0, C: 0, I: 4, A: 3, L: 0 },
  "JacketTshirt": { S: 6, P: 0, E: 0, C: 0, I: 0, A: 0, L: 0 },
  "JamesSpecial": { S: 0, P: 0, E: 0, C: 0, I: 0, A: 0, L: 0 },
  "JerichoSpecial": { S: 0, P: 0, E: 0, C: 0, I: 0, A: 0, L: 0 },
  "JobinsonsJersey": { S: 4, P: 4, E: 0, C: 4, I: 0, A: 4, L: 0 },
  "KingSpecial": { S: 0, P: 2, E: 0, C: 2, I: 0, A: 0, L: 1 },
  "KnightSpecial": { S: 2, P: 2, E: 0, C: 0, I: 0, A: 0, L: 1 },
  "LabCoat": { S: 0, P: 0, E: 0, C: 0, I: 3, A: 0, L: 0 },
  "LabCoat_Advanced": { S: 0, P: 0, E: 0, C: 0, I: 5, A: 0, L: 0 },
  "LabCoat_Expert": { S: 0, P: 0, E: 0, C: 0, I: 7, A: 0, L: 0 },
  "LibrarianSpecial": { S: 0, P: 0, E: 0, C: 0, I: 4, A: 0, L: 1 },
  "LifeguardOutfit": { S: 0, P: 4, E: 0, C: 0, I: 0, A: 0, L: 1 },
  "LoungeShirt": { S: 0, P: 6, E: 0, C: 0, I: 0, A: 0, L: 0 },
  "LucasSpecial": { S: 0, P: 2, E: 5, C: 0, I: 0, A: 0, L: 0 },
  "MaJuneJacket": { S: 0, P: 2, E: 0, C: 0, I: 0, A: 0, L: 2 },
  "MayorSpecial": { S: 0, P: 0, E: 0, C: 2, I: 2, A: 0, L: 1 },
  "MechanicJumpsuit": { S: 1, P: 0, E: 0, C: 1, I: 0, A: 0, L: 0 },
  "MetalArmor_Heavy": { S: 4, P: 0, E: 0, C: 0, I: 0, A: 0, L: 3 },
  "MetalArmor_Sturdy": { S: 3, P: 0, E: 0, C: 0, I: 0, A: 0, L: 2 },
  "MilitaryJumpsuit": { S: 3, P: 0, E: 0, C: 0, I: 0, A: 0, L: 0 },
  "MilitaryJumpsuit_Commander": { S: 7, P: 0, E: 0, C: 0, I: 0, A: 0, L: 0 },
  "MilitaryJumpsuit_Officer": { S: 5, P: 0, E: 0, C: 0, I: 0, A: 0, L: 0 },
  "MoiraSpecial": { S: 0, P: 0, E: 0, C: 0, I: 0, A: 0, L: 0 },
  "MojaveWastelandSurvivor": { S: 0, P: 1, E: 5, C: 0, I: 0, A: 0, L: 2 },
  "MoldaversArmor": { S: 2, P: 2, E: 4, C: 0, I: 0, A: 0, L: 4 },
  "MoviefanSpecial": { S: 0, P: 4, E: 0, C: 0, I: 0, A: 0, L: 1 },
  "MrBurkeSpecial": { S: 0, P: 0, E: 0, C: 0, I: 0, A: 0, L: 0 },
  "NinjaSuit": { S: 0, P: 0, E: 0, C: 0, I: 0, A: 4, L: 1 },
  "PiperSpecial": { S: 0, P: 2, E: 2, C: 0, I: 0, A: 2, L: 2 },
  "PolkaDotDress": { S: 1, P: 0, E: 0, C: 0, I: 1, A: 0, L: 0 },
  "PowerArmor": { S: 2, P: 3, E: 0, C: 0, I: 0, A: 0, L: 0 },
  "PowerArmor_51a": { S: 3, P: 1, E: 0, C: 0, I: 0, A: 0, L: 0 },
  "PowerArmor_51d": { S: 3, P: 2, E: 0, C: 0, I: 0, A: 0, L: 0 },
  "PowerArmor_51f": { S: 4, P: 3, E: 0, C: 0, I: 0, A: 0, L: 0 },
  "PowerArmor_MkI": { S: 3, P: 1, E: 1, C: 0, I: 0, A: 0, L: 0 },
  "PowerArmor_MkIV": { S: 4, P: 1, E: 1, C: 0, I: 0, A: 0, L: 0 },
  "PowerArmor_MkVI": { S: 5, P: 1, E: 1, C: 0, I: 0, A: 0, L: 0 },
  "PowerArmor_T45d": { S: 2, P: 4, E: 0, C: 0, I: 0, A: 0, L: 0 },
  "PowerArmor_T45f": { S: 2, P: 5, E: 0, C: 0, I: 0, A: 0, L: 0 },
  "PowerArmor_T60a": { S: 2, P: 0, E: 3, C: 0, I: 0, A: 0, L: 0 },
  "PowerArmor_T60d": { S: 2, P: 0, E: 4, C: 0, I: 0, A: 0, L: 0 },
  "PowerArmor_T60f": { S: 1, P: 1, E: 5, C: 0, I: 0, A: 0, L: 0 },
  "PrestonSpecial": { S: 2, P: 2, E: 0, C: 0, I: 2, A: 2, L: 0 },
  "PrinceSpecial": { S: 0, P: 0, E: 2, C: 0, I: 2, A: 0, L: 1 },
  "ProfessorSpecial": { S: 0, P: 0, E: 0, C: 0, I: 4, A: 0, L: 1 },
  "RadiationSuit": { S: 0, P: 1, E: 2, C: 0, I: 0, A: 0, L: 0 },
  "RadiationSuit_Advanced": { S: 0, P: 2, E: 3, C: 0, I: 0, A: 0, L: 0 },
  "RadiationSuit_Expert": { S: 0, P: 3, E: 4, C: 0, I: 0, A: 0, L: 0 },
  "RaiderArmor": { S: 0, P: 1, E: 0, C: 0, I: 0, A: 2, L: 0 },
  "RaiderArmor_Heavy": { S: 0, P: 3, E: 0, C: 0, I: 0, A: 4, L: 0 },
  "RaiderArmor_Sturdy": { S: 0, P: 2, E: 0, C: 0, I: 0, A: 3, L: 0 },
  "RiotGear": { S: 0, P: 1, E: 0, C: 0, I: 0, A: 1, L: 1 },
  "RiotGear_Heavy": { S: 0, P: 2, E: 0, C: 0, I: 0, A: 3, L: 2 },
  "RiotGear_Sturdy": { S: 0, P: 1, E: 0, C: 0, I: 0, A: 2, L: 2 },
  "RobCoRdSuit": { S: 0, P: 0, E: 2, C: 0, I: 4, A: 0, L: 0 },
  "RothchildSpecial": { S: 0, P: 2, E: 1, C: 2, I: 2, A: 0, L: 0 },
  "SantaSuit_Original": { S: 0, P: 4, E: 3, C: 4, I: 0, A: 0, L: 0 },
  "SarahSpecial": { S: 0, P: 0, E: 0, C: 0, I: 0, A: 0, L: 0 },
  "ScientistScrubs": { S: 0, P: 0, E: 0, C: 1, I: 2, A: 0, L: 0 },
  "ScientistScrubs_Commander": { S: 0, P: 0, E: 0, C: 3, I: 4, A: 0, L: 0 },
  "ScientistScrubs_Officer": { S: 0, P: 0, E: 0, C: 2, I: 3, A: 0, L: 0 },
  "ScifiSpecial": { S: 0, P: 0, E: 0, C: 0, I: 2, A: 2, L: 1 },
  "ScribeRobe": { S: 0, P: 0, E: 0, C: 3, I: 0, A: 2, L: 0 },
  "ScribeRobe_Elder": { S: 0, P: 0, E: 0, C: 4, I: 0, A: 3, L: 0 },
  "ScribeRobe_Initiate": { S: 0, P: 0, E: 0, C: 2, I: 0, A: 1, L: 0 },
  "SequinDress": { S: 0, P: 0, E: 0, C: 1, I: 0, A: 1, L: 0 },
  "SlasherSpecial": { S: 0, P: 0, E: 4, C: 0, I: 0, A: 0, L: 1 },
  "SodaFountainDress": { S: 0, P: 1, E: 1, C: 0, I: 1, A: 0, L: 1 },
  "SoldierSpecial": { S: 2, P: 0, E: 2, C: 0, I: 0, A: 0, L: 1 },
  "SpecialThemeHalloween": { S: 0, P: 0, E: 2, C: 0, I: 0, A: 3, L: 0 },
  "SpecialThemeHalloween2": { S: 2, P: 0, E: 0, C: 0, I: 0, A: 0, L: 3 },
  "SpecialThemeThanksGiving": { S: 0, P: 0, E: 0, C: 3, I: 2, A: 0, L: 0 },
  "SpecialThemeXmas": { S: 0, P: 3, E: 0, C: 2, I: 0, A: 0, L: 0 },
  "SpecialThemeXmas2": { S: 0, P: 0, E: 0, C: 0, I: 3, A: 0, L: 2 },
  "SportsfanSpecial": { S: 4, P: 0, E: 0, C: 0, I: 0, A: 0, L: 1 },
  "StarPaladinSpecial": { S: 0, P: 0, E: 0, C: 0, I: 0, A: 0, L: 0 },
  "SurgeonSpecial": { S: 0, P: 2, E: 0, C: 0, I: 0, A: 2, L: 1 },
  "SurvivorSpecial": { S: 2, P: 0, E: 0, C: 0, I: 0, A: 2, L: 1 },
  "Suspenders": { S: 0, P: 0, E: 4, C: 0, I: 0, A: 0, L: 0 },
  "SweaterVest": { S: 0, P: 1, E: 0, C: 0, I: 1, A: 0, L: 0 },
  "Swimsuit": { S: 0, P: 0, E: 2, C: 2, I: 0, A: 0, L: 1 },
  "SwingDress": { S: 0, P: 0, E: 0, C: 0, I: 0, A: 6, L: 0 },
  "SynthArmor_Heavy": { S: 0, P: 0, E: 4, C: 0, I: 3, A: 0, L: 0 },
  "ThreedogSpecial": { S: 0, P: 2, E: 0, C: 5, I: 0, A: 0, L: 0 },
  "TiedBlouse": { S: 4, P: 0, E: 0, C: 0, I: 0, A: 0, L: 0 },
  "UtilityJumpsuit": { S: 0, P: 3, E: 0, C: 0, I: 0, A: 0, L: 0 },
  "UtilityJumpsuit_Heavy": { S: 0, P: 7, E: 0, C: 0, I: 0, A: 0, L: 0 },
  "UtilityJumpsuit_Sturdy": { S: 0, P: 5, E: 0, C: 0, I: 0, A: 0, L: 0 },
  "Vault33Suit": { S: 0, P: 0, E: 0, C: 0, I: 0, A: 0, L: 0 },
  "Vest": { S: 0, P: 1, E: 0, C: 1, I: 1, A: 0, L: 1 },
  "WaitressUniform": { S: 0, P: 0, E: 0, C: 0, I: 0, A: 4, L: 0 },
  "WandererArmor": { S: 1, P: 0, E: 2, C: 0, I: 0, A: 0, L: 0 },
  "WandererArmor_Heavy": { S: 3, P: 0, E: 4, C: 0, I: 0, A: 0, L: 0 },
  "WandererArmor_Sturdy": { S: 2, P: 0, E: 3, C: 0, I: 0, A: 0, L: 0 },
  "WastelandSurgeon": { S: 0, P: 4, E: 0, C: 0, I: 0, A: 0, L: 3 },
  "WastelandSurgeon_Doctor": { S: 0, P: 3, E: 0, C: 0, I: 0, A: 0, L: 2 },
  "WastelandSurgeon_Settler": { S: 0, P: 2, E: 0, C: 0, I: 0, A: 0, L: 1 },
  "WilzigsTravelwear": { S: 0, P: 4, E: 2, C: 0, I: 0, A: 2, L: 4 },
  "WorkDress": { S: 0, P: 1, E: 1, C: 0, I: 0, A: 0, L: 0 },
  "WrestlerSpecial": { S: 2, P: 0, E: 2, C: 0, I: 0, A: 0, L: 1 },
  "jumpsuit": { S: 0, P: 0, E: 0, C: 0, I: 0, A: 0, L: 0 },
} as const;
