const CATS = {
    "abyssinian_r": 'Abyssinian - Resistance',
    "abyssinian_c": 'Abyssinian - Resistance',
    "abyssinian_l": 'Abyssinian - Resistance',
    "american_r": 'American Shorthair - Wasteland Caps Boost',
    "american_c": 'American Shorthair - Wasteland Caps Boost',
    "american_l": 'American Shorthair - Wasteland Caps Boost',
    "bombay_c": 'Bombay - Add Max HP',
    "bombay_r": 'Bombay - Add Max HP',
    "bombay_l": 'Bombay - Add Max HP',
    "british_c": 'British Shorthair - Healing Boost',
    "british_r": 'British Shorthair - Healing Boost',
    "british_l": 'British Shorthair - Healing Boost',
    "burmilla_r": 'Burmilla - Cheaper Crafting',
    "burmilla_l2": 'Burmilla - Cheaper Crafting',
    "burmilla_l": 'Burmilla - Cheaper Crafting',
    "havanabrown_r2": 'Havana Brown - Faster Crafting',
    "havanabrown_r": 'Havana Brown - Faster Crafting',
    "havanabrown_l": 'Havana Brown - Faster Crafting',
    "laperm_l3": 'LaPerm - Wasteland Junk Boost',
    "laperm_l": 'LaPerm - Wasteland Junk Boost',
    "laperm_l2": 'LaPerm - Wasteland Junk Boost',
    "lykoi_r": 'Lykoi - Damage Boost',
    "lykoi_c": 'Lykoi - Damage Boost',
    "lykoi_l": 'Lykoi - Damage Boost',
    "mainecoon_c": 'Maine Coon - Training Boost',
    "mainecoon_r": 'Maine Coon - Training Boost',
    "mainecoon_l": 'Maine Coon - Training Non-Stop Boost',
    "manx_l2": 'Manx - Child Multiplier',
    "manx_l": 'Manx - Child Multiplier',
    "manx_l3": 'Manx - Child Multiplier',
    "ocicat_r": 'Ocicat - Wasteland Item Boost',
    "ocicat_c": 'Ocicat - Wasteland Item Boost',
    "ocicat_l": 'Ocicat - Wasteland Item Boost',
    "pallascat_c": 'Pallas Cat - Wasteland Junk Boost',
    "pallascat_r": 'Pallas Cat - Wasteland Junk Boost',
    "pallascat_l": 'Pallas Cat - Wasteland Junk Boost',
    "persian_r": 'Persian - Happiness Boost',
    "persian_c": 'Persian - Happiness Boost',
    "persian_l_2": 'Persian - Special - Training Non-Stop Boost',
    "scottishfold_r": 'Scottish Fold - XP Boost',
    "scottishfold_c": 'Scottish Fold - XP Boost',
    "scottishfold_l": 'Scottish Fold - XP Boost',
    "siamese_c": 'Siamese - Rad Healing Boost',
    "siamese_r": 'Siamese - Rad Healing Boost',
    "siamese_l": 'Siamese - Rad Healing Boost',
    "somali_r2": 'Somali - Faster Crafting',
    "somali_r": 'Somali - Faster Crafting',
    "somali_l": 'Somali - Faster Crafting',
    "sphynx_c": 'Sphynx - Faster Wasteland Return Speed',
    "sphynx_r": 'Sphynx - Faster Wasteland Return Speed',
    "sphynx_l": 'Sphynx - Faster Wasteland Return Speed',
    "toyger_r": 'Toyger - Mysterious Magnet',
    "toyger_c": 'Toyger - Mysterious Magnet',
    "toyger_l": 'Toyger - Mysterious Magnet',
    "turkishvan_r": 'Turkish Van - Child Special Boost',
    "turkishvan_l2": 'Turkish Van - Child Special Boost',
    "turkishvan_l": 'Turkish Van - Child Special Boost',
} as const;

const DOGS = {
    "akita_r": 'Akita - Mysterious Magnet',
    "akita_l2": 'Akita - Mysterious Magnet',
    "akita_l": 'Akita - Mysterious Magnet',
    "australianshepherd_r2": 'Australian Shepherd - Child Special Boost',
    "australianshepherd_r": 'Australian Shepherd - Child Special Boost',
    "australianshepherd_l": 'Australian Shepherd - Child Special Boost',
    "blacklab_r": 'Black Labrador - Training Boost',
    "blacklab_c": 'Black Labrador - Training Boost',
    "blacklab_l": 'Black Labrador - Training Non-Stop Boost',
    "bloodhound_l": 'Bloodhound - Wasteland Junk Boost',
    "bloodhound_l3": 'Bloodhound - Wasteland Junk Boost',
    "bloodhound_l2": 'Bloodhound - Wasteland Junk Boost',
    "boxer_c": 'Boxer - XP Boost',
    "boxer_r": 'Boxer - XP Boost',
    "boxer_l": 'Boxer - XP Boost',
    "brittany_c": 'Brittany - Faster And Cheaper Crafting',
    "brittany_r": 'Brittany - Faster And Cheaper Crafting',
    "brittany_l": 'Brittany - Faster And Cheaper Crafting',
    "cattledog_c": 'Cattle Dog - Wasteland Caps Boost',
    "cattledog_r": 'Cattle Dog - Wasteland Caps Boost',
    "cattledog_l": 'Cattle Dog - Wasteland Caps Boost',
    "collie_r": 'Collie - Cheaper Crafting',
    "collie_c": 'Collie - Cheaper Crafting',
    "collie_l": 'Collie - Cheaper Crafting',
    "dalmatian_r": 'Dalmatian - Child Multiplier',
    "dalmatian_l2": 'Dalmatian - Child Multiplier',
    "dalmatian_l": 'Dalmatian - Child Multiplier',
    "doberman_c": 'Doberman - Healing Boost',
    "doberman_r": 'Doberman - Healing Boost',
    "doberman_l": 'Doberman - Healing Boost',
    "englishmastiff_r2": 'English Mastiff - Cheaper Crafting',
    "englishmastiff_r": 'English Mastiff - Cheaper Crafting',
    "englishmastiff_l": 'English Mastiff - Cheaper Crafting',
    "germanpointer_r": 'German Pointer - Rad Healing Boost',
    "germanpointer_c": 'German Pointer - Rad Healing Boost',
    "germanpointer_l2": 'German Pointer - Faster Wasteland Return Speed',
    "germanpointer_l": 'German Pointer - Rad Healing Boost',
    "germanshepherd_r": 'German Shepherd - Objective Multiplier',
    "germanshepherd_l": 'German Shepherd - Objective Multiplier',
    "goldenret_c": 'Golden Retriever - Wasteland Item Boost',
    "goldenret_r": 'Golden Retriever - Wasteland Item Boost',
    "goldenret_l": 'Golden Retriever - Wasteland Item Boost',
    "greyhound_c": 'Greyhound - Faster Crafting',
    "greyhound_r": 'Greyhound - Faster Crafting',
    "greyhound_l": 'Greyhound - Faster Crafting',
    "husky_r": 'Husky - Faster Wasteland Return Speed',
    "husky_c": 'Husky - Faster Wasteland Return Speed',
    "husky_l": 'Husky - Faster Wasteland Return Speed',
    "pitbullterrier_l": 'Pit Bull Terrier - Damage Boost',
    "pitbullterrier_l2": 'Pit Bull Terrier - Damage Boost',
    "pitbullterrier_l3": 'Pit Bull Terrier - Damage Boost',
    "poodle_r": 'Poodle - Happiness Boost',
    "poodle_c": 'Poodle - Happiness Boost',
    "poodle_l": 'Poodle - Happiness Boost',
    "rottweiler_r": 'Rottweiler - Add Max HP',
    "rottweiler_c": 'Rottweiler - Add Max HP',
    "rottweiler_l": 'Rottweiler - Add Max HP',
    "stbernard_r": 'St. Bernard - Wasteland Junk Boost',
    "stbernard_c": 'St. Bernard - Wasteland Junk Boost',
    "stbernard_l": 'St. Bernard - Wasteland Junk Boost',
} as const;

const BIRDS = {
    "militarymacaw_l2": 'Military Macaw - Damage Boost',
    "militarymacaw_l": 'Military Macaw - Damage Boost',
    "militarymacaw_r": 'Military Macaw - Damage Boost',
    "blueyellowmacaw_l": 'Blue & Yellow Macaw - Objective Multiplier',
    "blueyellowmacaw_l2": 'Blue & Yellow Macaw - Objective Multiplier',
    "scarletmacaw_c": 'Scarlet Macaw - Resistance',
    "scarletmacaw_r": 'Scarlet Macaw - Resistance',
    "scarletmacaw_l": 'Scarlet Macaw - Resistance'
} as const;

export const PET_LIST = {
    ...CATS,
    ...DOGS,
    ...BIRDS
} as const;
