const CATS = {
    "abyssinian_r": 'Abyssinian - Resistance',
    "abyssinian_c": 'Abyssinian - Resistance',
    "abyssinian_l": 'Abyssinian - Resistance',
    "american_r": 'American Shorthair - Wasteland Caps Boost',
    "american_c": 'American Shorthair - Wasteland Caps Boost',
    "american_l": 'American Shorthair - Wasteland Caps Boost',
    "bombay_c": 'Bombay - Add Max HP',
    "bombay_r": 'Bombay - Add Max HP',
    "bombay_l": 'Bombay - Add Max HP',
    "british_c": 'British Shorthair - Healing Boost',
    "british_r": 'British Shorthair - Healing Boost',
    "british_l": 'British Shorthair - Healing Boost',
    "burmilla_r": 'Burmilla - Cheaper Crafting',
    "burmilla_l2": 'Burmilla - Cheaper Crafting',
    "burmilla_l": 'Burmilla - Cheaper Crafting',
    "havanabrown_r2": 'Havana Brown - Faster Crafting',
    "havanabrown_r": 'Havana Brown - Faster Crafting',
    "havanabrown_l": 'Havana Brown - Faster Crafting',
    "laperm_l3": 'LaPerm - Wasteland Junk Boost',
    "laperm_l": 'LaPerm - Wasteland Junk Boost',
    "laperm_l2": 'LaPerm - Wasteland Junk Boost',
    "lykoi_r": 'Lykoi - Damage Boost',
    "lykoi_c": 'Lykoi - Damage Boost',
    "lykoi_l": 'Lykoi - Damage Boost',
    "mainecoon_c": 'Maine Coon - Training Boost',
    "mainecoon_r": 'Maine Coon - Training Boost',
    "mainecoon_l": 'Maine Coon - Training Non-Stop Boost',
    "manx_l2": 'Manx - Child Multiplier',
    "manx_l": 'Manx - Child Multiplier',
    "manx_l3": 'Manx - Child Multiplier',
    "ocicat_r": 'Ocicat - Wasteland Item Boost',
    "ocicat_c": 'Ocicat - Wasteland Item Boost',
    "ocicat_l": 'Ocicat - Wasteland Item Boost',
    "pallascat_c": 'Pallas Cat - Wasteland Junk Boost',
    "pallascat_r": 'Pallas Cat - Wasteland Junk Boost',
    "pallascat_l": 'Pallas Cat - Wasteland Junk Boost',
    "persian_r": 'Persian - Happiness Boost',
    "persian_c": 'Persian - Happiness Boost',
    "persian_l_2": 'Persian - Special - Training Non-Stop Boost',
    "scottishfold_r": 'Scottish Fold - XP Boost',
    "scottishfold_c": 'Scottish Fold - XP Boost',
    "scottishfold_l": 'Scottish Fold - XP Boost',
    "siamese_c": 'Siamese - Rad Healing Boost',
    "siamese_r": 'Siamese - Rad Healing Boost',
    "siamese_l": 'Siamese - Rad Healing Boost',
    "somali_r2": 'Somali - Faster Crafting',
    "somali_r": 'Somali - Faster Crafting',
    "somali_l": 'Somali - Faster Crafting',
    "sphynx_c": 'Sphynx - Faster Wasteland Return Speed',
    "sphynx_r": 'Sphynx - Faster Wasteland Return Speed',
    "sphynx_l": 'Sphynx - Faster Wasteland Return Speed',
    "toyger_r": 'Toyger - Mysterious Magnet',
    "toyger_c": 'Toyger - Mysterious Magnet',
    "toyger_l": 'Toyger - Mysterious Magnet',
    "turkishvan_r": 'Turkish Van - Child Special Boost',
    "turkishvan_l2": 'Turkish Van - Child Special Boost',
    "turkishvan_l": 'Turkish Van - Child Special Boost',
} as const;

const DOGS = {
    "akita_r": 'Akita - Mysterious Magnet',
    "akita_l2": 'Akita - Mysterious Magnet',
    "akita_l": 'Akita - Mysterious Magnet',
    "australianshepherd_r2": 'Australian Shepherd - Child Special Boost',
    "australianshepherd_r": 'Australian Shepherd - Child Special Boost',
    "australianshepherd_l": 'Australian Shepherd - Child Special Boost',
    "blacklab_r": 'Black Labrador - Training Boost',
    "blacklab_c": 'Black Labrador - Training Boost',
    "blacklab_l": 'Black Labrador - Training Non-Stop Boost',
    "bloodhound_l": 'Bloodhound - Wasteland Junk Boost',
    "bloodhound_l3": 'Bloodhound - Wasteland Junk Boost',
    "bloodhound_l2": 'Bloodhound - Wasteland Junk Boost',
    "boxer_c": 'Boxer - XP Boost',
    "boxer_r": 'Boxer - XP Boost',
    "boxer_l": 'Boxer - XP Boost',
    "brittany_c": 'Brittany - Faster And Cheaper Crafting',
    "brittany_r": 'Brittany - Faster And Cheaper Crafting',
    "brittany_l": 'Brittany - Faster And Cheaper Crafting',
    "cattledog_c": 'Cattle Dog - Wasteland Caps Boost',
    "cattledog_r": 'Cattle Dog - Wasteland Caps Boost',
    "cattledog_l": 'Cattle Dog - Wasteland Caps Boost',
    "collie_r": 'Collie - Cheaper Crafting',
    "collie_c": 'Collie - Cheaper Crafting',
    "collie_l": 'Collie - Cheaper Crafting',
    "dalmatian_r": 'Dalmatian - Child Multiplier',
    "dalmatian_l2": 'Dalmatian - Child Multiplier',
    "dalmatian_l": 'Dalmatian - Child Multiplier',
    "doberman_c": 'Doberman - Healing Boost',
    "doberman_r": 'Doberman - Healing Boost',
    "doberman_l": 'Doberman - Healing Boost',
    "englishmastiff_r2": 'English Mastiff - Cheaper Crafting',
    "englishmastiff_r": 'English Mastiff - Cheaper Crafting',
    "englishmastiff_l": 'English Mastiff - Cheaper Crafting',
    "germanpointer_r": 'German Pointer - Rad Healing Boost',
    "germanpointer_c": 'German Pointer - Rad Healing Boost',
    "germanpointer_l2": 'German Pointer - Faster Wasteland Return Speed',
    "germanpointer_l": 'German Pointer - Rad Healing Boost',
    "germanshepherd_r": 'German Shepherd - Objective Multiplier',
    "germanshepherd_l": 'German Shepherd - Objective Multiplier',
    "goldenret_c": 'Golden Retriever - Wasteland Item Boost',
    "goldenret_r": 'Golden Retriever - Wasteland Item Boost',
    "goldenret_l": 'Golden Retriever - Wasteland Item Boost',
    "greyhound_c": 'Greyhound - Faster Crafting',
    "greyhound_r": 'Greyhound - Faster Crafting',
    "greyhound_l": 'Greyhound - Faster Crafting',
    "husky_r": 'Husky - Faster Wasteland Return Speed',
    "husky_c": 'Husky - Faster Wasteland Return Speed',
    "husky_l": 'Husky - Faster Wasteland Return Speed',
    "pitbullterrier_l": 'Pit Bull Terrier - Damage Boost',
    "pitbullterrier_l2": 'Pit Bull Terrier - Damage Boost',
    "pitbullterrier_l3": 'Pit Bull Terrier - Damage Boost',
    "poodle_r": 'Poodle - Happiness Boost',
    "poodle_c": 'Poodle - Happiness Boost',
    "poodle_l": 'Poodle - Happiness Boost',
    "rottweiler_r": 'Rottweiler - Add Max HP',
    "rottweiler_c": 'Rottweiler - Add Max HP',
    "rottweiler_l": 'Rottweiler - Add Max HP',
    "stbernard_r": 'St. Bernard - Wasteland Junk Boost',
    "stbernard_c": 'St. Bernard - Wasteland Junk Boost',
    "stbernard_l": 'St. Bernard - Wasteland Junk Boost',
} as const;

const BIRDS = {
    "militarymacaw_l2": 'Military Macaw - Damage Boost',
    "militarymacaw_l": 'Military Macaw - Damage Boost',
    "militarymacaw_r": 'Military Macaw - Damage Boost',
    "blueyellowmacaw_l": 'Blue & Yellow Macaw - Objective Multiplier',
    "blueyellowmacaw_l2": 'Blue & Yellow Macaw - Objective Multiplier',
    "scarletmacaw_c": 'Scarlet Macaw - Resistance',
    "scarletmacaw_r": 'Scarlet Macaw - Resistance',
    "scarletmacaw_l": 'Scarlet Macaw - Resistance'
} as const;

export const PET_LIST = {
    ...CATS,
    ...DOGS,
    ...BIRDS
} as const;

export const petBonusMap: { [key: string]: { uniqueName: string; bonus: string; bonusValue: number } } = {
    // Cats
    "abyssinian_r": { uniqueName: "Abyssinian", bonus: "Resistance", bonusValue: 38 },
    "abyssinian_c": { uniqueName: "Abyssinian", bonus: "Resistance", bonusValue: 22 },
    "abyssinian_l": { uniqueName: "Zula", bonus: "Resistance", bonusValue: 48 },
    "american_r": { uniqueName: "American Shorthair", bonus: "WastelandCapsBoost", bonusValue: 25.5 },
    "american_c": { uniqueName: "American Shorthair", bonus: "WastelandCapsBoost", bonusValue: 10.5 },
    "american_l": { uniqueName: "Sterling", bonus: "WastelandCapsBoost", bonusValue: 40.5 },
    "bombay_c": { uniqueName: "Bombay", bonus: "AddMaxHP", bonusValue: 29 },
    "bombay_r": { uniqueName: "Bombay", bonus: "AddMaxHP", bonusValue: 62 },
    "bombay_l": { uniqueName: "Shadow", bonus: "AddMaxHP", bonusValue: 95.5 },
    "british_c": { uniqueName: "British Shorthair", bonus: "HealingBoost", bonusValue: 2 },
    "british_r": { uniqueName: "British Shorthair", bonus: "HealingBoost", bonusValue: 3 },
    "british_l": { uniqueName: "Ashes", bonus: "HealingBoost", bonusValue: 4 },
    "burmilla_r": { uniqueName: "Burmilla", bonus: "CheaperCrafting", bonusValue: 8 },
    "burmilla_l2": { uniqueName: "Cloudy", bonus: "CheaperCrafting", bonusValue: 17 },
    "burmilla_l": { uniqueName: "Diamond", bonus: "CheaperCrafting", bonusValue: 28 },
    "havanabrown_r2": { uniqueName: "Havana Brown", bonus: "FasterCrafting", bonusValue: 10.5 },
    "havanabrown_r": { uniqueName: "Havana Brown", bonus: "FasterCrafting", bonusValue: 25.5 },
    "havanabrown_l": { uniqueName: "Merlin", bonus: "FasterCrafting", bonusValue: 40.5 },
    "laperm_l3": { uniqueName: "Luna", bonus: "WastelandJunkBoost", bonusValue: 62 },
    "laperm_l": { uniqueName: "Pouncer", bonus: "WastelandJunkBoost", bonusValue: 95.5 },
    "laperm_l2": { uniqueName: "Static", bonus: "WastelandJunkBoost", bonusValue: 29 },
    "lykoi_r": { uniqueName: "Lykoi", bonus: "DamageBoost", bonusValue: 4 },
    "lykoi_c": { uniqueName: "Lykoi", bonus: "DamageBoost", bonusValue: 2 },
    "lykoi_l": { uniqueName: "Calypso", bonus: "DamageBoost", bonusValue: 6 },
    "mainecoon_c": { uniqueName: "Maine Coon", bonus: "TrainingBoost", bonusValue: 8 },
    "mainecoon_r": { uniqueName: "Maine Coon", bonus: "TrainingBoost", bonusValue: 18 },
    "mainecoon_l": { uniqueName: "Bangor", bonus: "TrainingNonStopBoost", bonusValue: 28 },
    "manx_l2": { uniqueName: "Genius", bonus: "ChildMultiplier", bonusValue: 25 },
    "manx_l": { uniqueName: "Shakespeare", bonus: "ChildMultiplier", bonusValue: 75 },
    "manx_l3": { uniqueName: "Stubbs", bonus: "ChildMultiplier", bonusValue: 50 },
    "ocicat_r": { uniqueName: "Ocicat", bonus: "WastelandItemBoost", bonusValue: 18 },
    "ocicat_c": { uniqueName: "Ocicat", bonus: "WastelandItemBoost", bonusValue: 8 },
    "ocicat_l": { uniqueName: "Speckle", bonus: "WastelandItemBoost", bonusValue: 28 },
    "pallascat_c": { uniqueName: "Pallass Cat", bonus: "WastelandJunkBoost", bonusValue: 29 },
    "pallascat_r": { uniqueName: "Pallass Cat", bonus: "WastelandJunkBoost", bonusValue: 62 },
    "pallascat_l": { uniqueName: "Cinder", bonus: "WastelandJunkBoost", bonusValue: 95.5 },
    "persian_r": { uniqueName: "Persian", bonus: "HappinessBoost", bonusValue: 62 },
    "persian_c": { uniqueName: "Persian", bonus: "HappinessBoost", bonusValue: 29 },
    "persian_l": { uniqueName: "Mr, Pebbles", bonus: "HappinessBoost", bonusValue: 95.5 },
    "persian_l_2": { uniqueName: "Pugsley", bonus: "TrainingNonStopBoost", bonusValue: 28 },
    "scottishfold_r": { uniqueName: "Scottish Fold", bonus: "XPBoost", bonusValue: 25.5 },
    "scottishfold_c": { uniqueName: "Scottish Fold", bonus: "XPBoost", bonusValue: 10.5 },
    "scottishfold_l": { uniqueName: "Ginger", bonus: "XPBoost", bonusValue: 40.5 },
    "siamese_c": { uniqueName: "Siamese", bonus: "RadHealingBoost", bonusValue: 2 },
    "siamese_r": { uniqueName: "Siamese", bonus: "RadHealingBoost", bonusValue: 3 },
    "siamese_l": { uniqueName: "Goblet", bonus: "RadHealingBoost", bonusValue: 4 },
    "somali_r2": { uniqueName: "Somali", bonus: "FasterCrafting", bonusValue: 10.5 },
    "somali_r": { uniqueName: "Somali", bonus: "FasterCrafting", bonusValue: 25.5 },
    "somali_l": { uniqueName: "Saffron", bonus: "FasterCrafting", bonusValue: 40.5 },
    "sphynx_c": { uniqueName: "Sphynx", bonus: "FasterWastelandReturnSpeed", bonusValue: 1.25 },
    "sphynx_r": { uniqueName: "Sphynx", bonus: "FasterWastelandReturnSpeed", bonusValue: 2 },
    "sphynx_l": { uniqueName: "Bastet", bonus: "FasterWastelandReturnSpeed", bonusValue: 4 },
    "toyger_r": { uniqueName: "Toyger", bonus: "MysteriousMagnet", bonusValue: 5 },
    "toyger_c": { uniqueName: "Toyger", bonus: "MysteriousMagnet", bonusValue: 2.5 },
    "toyger_l": { uniqueName: "Kato", bonus: "MysteriousMagnet", bonusValue: 7.5 },
    "turkishvan_r": { uniqueName: "Turkish Van", bonus: "ChildSpecialBoost", bonusValue: 1 },
    "turkishvan_l2": { uniqueName: "Pumpkin", bonus: "ChildSpecialBoost", bonusValue: 2 },
    "turkishvan_l": { uniqueName: "Duchess", bonus: "ChildSpecialBoost", bonusValue: 3 },

    // Dogs
    "akita_r": { uniqueName: "Akita", bonus: "MysteriousMagnet", bonusValue: 2.5 },
    "akita_l2": { uniqueName: "Kabosu", bonus: "MysteriousMagnet", bonusValue: 5 },
    "akita_l": { uniqueName: "Kuma", bonus: "MysteriousMagnet", bonusValue: 7.5 },
    "australianshepherd_r2": { uniqueName: "Australian Shepherd", bonus: "ChildSpecialBoost", bonusValue: 1 },
    "australianshepherd_r": { uniqueName: "Australian Shepherd", bonus: "ChildSpecialBoost", bonusValue: 2 },
    "australianshepherd_l": { uniqueName: "Bandit", bonus: "ChildSpecialBoost", bonusValue: 3 },
    "blacklab_r": { uniqueName: "Black Lab", bonus: "TrainingBoost", bonusValue: 18 },
    "blacklab_c": { uniqueName: "Black Lab", bonus: "TrainingBoost", bonusValue: 8 },
    "blacklab_l": { uniqueName: "Muttface", bonus: "TrainingNonStopBoost", bonusValue: 28 },
    "bloodhound_l": { uniqueName: "Duke", bonus: "WastelandJunkBoost", bonusValue: 95.5 },
    "bloodhound_l3": { uniqueName: "Moose", bonus: "WastelandJunkBoost", bonusValue: 62 },
    "bloodhound_l2": { uniqueName: "Valentine", bonus: "WastelandJunkBoost", bonusValue: 29 },
    "boxer_c": { uniqueName: "Boxer", bonus: "XPBoost", bonusValue: 10.5 },
    "boxer_r": { uniqueName: "Boxer", bonus: "XPBoost", bonusValue: 25.5 },
    "boxer_l": { uniqueName: "Scavver", bonus: "XPBoost", bonusValue: 40.5 },
    "brittany_c": { uniqueName: "Brittany", bonus: "FasterAndCheaperCrafting", bonusValue: 8 },
    "brittany_r": { uniqueName: "Brittany", bonus: "FasterAndCheaperCrafting", bonusValue: 18 },
    "brittany_l": { uniqueName: "Gaston", bonus: "FasterAndCheaperCrafting", bonusValue: 28 },
    "cattledog_c": { uniqueName: "Cattle Dog", bonus: "WastelandCapsBoost", bonusValue: 10.5 },
    "cattledog_r": { uniqueName: "Cattle Dog", bonus: "WastelandCapsBoost", bonusValue: 25.5 },
    "cattledog_l": { uniqueName: "Four Score", bonus: "WastelandCapsBoost", bonusValue: 40.5 },
    "collie_r": { uniqueName: "Collie", bonus: "CheaperCrafting", bonusValue: 18 },
    "collie_c": { uniqueName: "Collie", bonus: "CheaperCrafting", bonusValue: 8 },
    "collie_l": { uniqueName: "Pal", bonus: "CheaperCrafting", bonusValue: 28 },
    "dalmatian_r": { uniqueName: "Dalmatian", bonus: "ChildMultiplier", bonusValue: 25 },
    "dalmatian_l2": { uniqueName: "Lucky", bonus: "ChildMultiplier", bonusValue: 50 },
    "dalmatian_l": { uniqueName: "Pongo", bonus: "ChildMultiplier", bonusValue: 75 },
    "doberman_c": { uniqueName: "Doberman", bonus: "HealingBoost", bonusValue: 2 },
    "doberman_r": { uniqueName: "Doberman", bonus: "HealingBoost", bonusValue: 3 },
    "doberman_l": { uniqueName: "Apolda", bonus: "HealingBoost", bonusValue: 4 },
    "englishmastiff_r2": { uniqueName: "English Mastiff", bonus: "CheaperCrafting", bonusValue: 8 },
    "englishmastiff_r": { uniqueName: "English Mastiff", bonus: "CheaperCrafting", bonusValue: 18 },
    "englishmastiff_l": { uniqueName: "Goliath", bonus: "CheaperCrafting", bonusValue: 28 },
    "germanpointer_r": { uniqueName: "German Pointer", bonus: "RadHealingBoost", bonusValue: 3 },
    "germanpointer_c": { uniqueName: "German Pointer", bonus: "RadHealingBoost", bonusValue: 2 },
    "germanpointer_l2": { uniqueName: "Cocoa Bean", bonus: "FasterWastelandReturnSpeed", bonusValue: 4 },
    "germanpointer_l": { uniqueName: "Mr, Peepers", bonus: "RadHealingBoost", bonusValue: 4 },
    "germanshepherd_r": { uniqueName: "German Shepherd", bonus: "ObjectiveMultiplier", bonusValue: 2 },
    "germanshepherd_l": { uniqueName: "Dogmeat", bonus: "ObjectiveMultiplier", bonusValue: 3 },
    "goldenret_c": { uniqueName: "Golden Retriever", bonus: "WastelandItemBoost", bonusValue: 8 },
    "goldenret_r": { uniqueName: "Golden Retriever", bonus: "WastelandItemBoost", bonusValue: 18 },
    "goldenret_l": { uniqueName: "Cindy", bonus: "WastelandItemBoost", bonusValue: 28 },
    "greyhound_c": { uniqueName: "Greyhound", bonus: "FasterCrafting", bonusValue: 10.5 },
    "greyhound_r": { uniqueName: "Greyhound", bonus: "FasterCrafting", bonusValue: 25.5 },
    "greyhound_l": { uniqueName: "Little Helper", bonus: "FasterCrafting", bonusValue: 40.5 },
    "husky_r": { uniqueName: "Husky", bonus: "FasterWastelandReturnSpeed", bonusValue: 2 },
    "husky_c": { uniqueName: "Husky", bonus: "FasterWastelandReturnSpeed", bonusValue: 1.25 },
    "husky_l": { uniqueName: "Trench", bonus: "FasterWastelandReturnSpeed", bonusValue: 4 },
    "pitbullterrier_l": { uniqueName: "Hulk", bonus: "DamageBoost", bonusValue: 6 },
    "pitbullterrier_l2": { uniqueName: "Ranger", bonus: "DamageBoost", bonusValue: 2 },
    "pitbullterrier_l3": { uniqueName: "Titan", bonus: "DamageBoost", bonusValue: 4 },
    "poodle_r": { uniqueName: "Poodle", bonus: "HappinessBoost", bonusValue: 62 },
    "poodle_c": { uniqueName: "Poodle", bonus: "HappinessBoost", bonusValue: 29 },
    "poodle_l": { uniqueName: "Lord Puffington", bonus: "HappinessBoost", bonusValue: 95.5 },
    "rottweiler_r": { uniqueName: "Rottweiler", bonus: "AddMaxHP", bonusValue: 62 },
    "rottweiler_c": { uniqueName: "Rottweiler", bonus: "AddMaxHP", bonusValue: 29 },
    "rottweiler_l": { uniqueName: "Maizie Rai", bonus: "AddMaxHP", bonusValue: 95.5 },
    "stbernard_r": { uniqueName: "St, Bernard", bonus: "WastelandJunkBoost", bonusValue: 62 },
    "stbernard_c": { uniqueName: "St, Bernard", bonus: "WastelandJunkBoost", bonusValue: 29 },
    "stbernard_l": { uniqueName: "Barry", bonus: "WastelandJunkBoost", bonusValue: 95.5 },

    // Parrots/Macaws
    "militarymacaw_l2": { uniqueName: "Butch", bonus: "DamageBoost", bonusValue: 4 },
    "militarymacaw_l": { uniqueName: "Polly", bonus: "DamageBoost", bonusValue: 6 },
    "militarymacaw_r": { uniqueName: "Military Macaw", bonus: "DamageBoost", bonusValue: 2 },
    "blueyellowmacaw_l": { uniqueName: "Pip", bonus: "ObjectiveMultiplier", bonusValue: 3 },
    "blueyellowmacaw_l2": { uniqueName: "Vinnie", bonus: "ObjectiveMultiplier", bonusValue: 2 },
    "scarletmacaw_c": { uniqueName: "Pirate Parrot", bonus: "Resistance", bonusValue: 22 },
    "scarletmacaw_r": { uniqueName: "Pirate Parrot", bonus: "Resistance", bonusValue: 38 },
    "scarletmacaw_l": { uniqueName: "Wanderer", bonus: "Resistance", bonusValue: 48 }
};
