export const ROOM_UNLOCKS = [
  "StorageUnlock",
  "MedbayUnlock", 
  "SciencelabUnlock",
  "OverseerUnlock",
  "RadioStationUnlock",
  "WeaponFactoryUnlock",
  "GymUnlock",
  "DojoUnlock",
  "ArmoryUnlock",
  "ClassUnlock",
  "OutfitFactoryUnlock",
  "CardioUnlock",
  "BarUnlock",
  "GameRoomUnlock",
  "BarberShopUnlock",
  "PowerPlantUnlock",
  "WaterroomUnlock",
  "HydroponicUnlock",
  "NukacolaUnlock",
  "DesignFactoryUnlock"
] as const;