export const WEAPON_LIST = {
  "032Pistol": '.32 Pistol',
  "Pistol": '10mm Pistol',
  "GaussRifle_Accelerated": 'Accelerated Gauss Rifle',
  "Railgun_Accelerated": 'Accelerated Railway Rifle',
  "PlasmaThrower_Agitated": 'Agitated Plasma Thrower',
  "AlienBlaster": 'Alien Blaster',
  "AmataPistol": "Amata's Pistol",
  "AlienBlaster_Amplified": 'Amplified Alien Blaster',
  "GatlingLaser_Amplified": 'Amplified Gatling Laser',
  "LaserPistol_Amplified": 'Amplified Laser Pistol',
  "LaserRifle_Amplified": 'Amplified Laser Rifle',
  "PlasmaPistol_Amplified": 'Amplified Plasma Pistol',
  "PlasmaRifle_Amplified": 'Amplified Plasma Rifle',
  "InstitutePistol_Apotheosis": 'Apotheosis',
  "032Pistol_ArmorPiercing": 'Armor Piercing .32 Pistol',
  "Pistol_ArmorPiercing": 'Armor Piercing 10mm Pistol',
  "AssaultRifle_ArmorPiercing": 'Armor Piercing Assault Rifle',
  "BBGun_ArmorPiercing": 'Armor Piercing BB Gun',
  "HuntingRifle_ArmorPiercing": 'Armor Piercing Hunting Rifle',
  "Rifle_ArmorPiercing": 'Armor Piercing Lever-Action Rifle',
  "Minigun_ArmorPiercing": 'Armor Piercing Minigun',
  "Magnum_ArmorPiercing": 'Armor Piercing Scoped .44',
  "SniperRifle_ArmorPiercing": 'Armor Piercing Sniper Rifle',
  "AssaultRifle": 'Assault Rifle',
  "PipePistol_Auto": 'Auto Pipe Pistol',
  "Melee_BaseballBat": 'Baseball Bat',
  "PipeRifle_Bayoneted": 'Bayoneted Pipe Rifle',
  "BBGun": 'BB Gun',
  "PipeRifle_BigSister": 'Big Sister',
  "Magnum_Blackhawk": 'Blackhawk',
  "PlasmaThrower_Boosted": 'Boosted Plasma Thrower',
  "Flamer_Burnmaster": 'Burnmaster',
  "Melee_ButcherKnife": 'Butcher Knife',
  "PipeRifle_Calibrated": 'Calibrated Pipe Rifle',
  "CombatShotgun_CharonsShotgun": "Charon's Shotgun",
  "CombatShotgun": 'Combat Shotgun',
  "AlienBlaster_Destabilizer": 'Destabilizer',
  "CombatShotgun_DoubleBarrelled": 'Double-Barrel Combat Shotgun',
  "SawedOffShotgun_DoubleBarrelled": 'Double-Barrel Sawed-Off Shotgun',
  "Shotgun_DoubleBarrelled": 'Double-Barrel Shotgun',
  "PlasmaThrower_DragonsMaw": "Dragon's Maw",
  "JunkJet_Electrified": 'Electrified Junk Jet',
  "032Pistol_Enhanced": 'Enhanced .32 Pistol',
  "Pistol_Enhanced": 'Enhanced 10mm Pistol',
  "AssaultRifle_Enhanced": 'Enhanced Assault Rifle',
  "BBGun_Enhanced": 'Enhanced BB Gun',
  "CombatShotgun_Enhanced": 'Enhanced Combat Shotgun',
  "Fatman_Enhanced": 'Enhanced Fat Man',
  "Flamer_Enhanced": 'Enhanced Flamer',
  "GaussRifle_Enhanced": 'Enhanced Gauss Rifle',
  "HuntingRifle_Enhanced": 'Enhanced Hunting Rifle',
  "Rifle_Enhanced": 'Enhanced Lever-Action Rifle',
  "Minigun_Enhanced": 'Enhanced Minigun',
  "MissilLauncher_Enhanced": 'Enhanced Missile Launcher',
  "Railgun_Enhanced": 'Enhanced Railway Rifle',
  "SawedOffShotgun_Enhanced": 'Enhanced Sawed-Off Shotgun',
  "Magnum_Enhanced": 'Enhanced Scoped .44',
  "Shotgun_Enhanced": 'Enhanced Shotgun',
  "SniperRifle_Enhanced": 'Enhanced Sniper Rifle',
  "InstituteRifle_Excited": 'Excited Institute Rifle',
  "Shotgun_FarmersDaughter": "Farmer's Daughter",
  "Fatman": 'Fat Man',
  "Melee_FireHydrantBat": 'Fire Hydrant Bat',
  "Fist": 'Fist',
  "Flamer": 'Flamer',
  "JunkJet_Flaming": 'Flaming Junk Jet',
  "AlienBlaster_Focused": 'Focused Alien Blaster',
  "GatlingLaser_Focused": 'Focused Gatling Laser',
  "LaserPistol_Focused": 'Focused Laser Pistol',
  "LaserRifle_Focused": 'Focused Laser Rifle',
  "PlasmaPistol_Focused": 'Focused Plasma Pistol',
  "PlasmaRifle_Focused": 'Focused Plasma Rifle',
  "GatlingLaser": 'Gatling Laser',
  "GaussRifle": 'Gauss Rifle',
  "Fatman_Guided": 'Guided Fat Man',
  "MissilLauncher_Guided": 'Guided Missile Launcher',
  "PipePistol_HairTrigger": 'Hair Trigger Pipe Pistol',
  "032Pistol_Hardened": 'Hardened .32 Pistol',
  "Pistol_Hardened": 'Hardened 10mm Pistol',
  "AssaultRifle_Hardened": 'Hardened Assault Rifle',
  "BBGun_Hardened": 'Hardened BB Gun',
  "CombatShotgun_Hardened": 'Hardened Combat Shotgun',
  "Fatman_Hardened": 'Hardened Fat Man',
  "Flamer_Hardened": 'Hardened Flamer',
  "GaussRifle_Hardened": 'Hardened Gauss Rifle',
  "HuntingRifle_Hardened": 'Hardened Hunting Rifle',
  "Rifle_Hardened": 'Hardened Lever-Action Rifle',
  "Minigun_Hardened": 'Hardened Minigun',
  "MissilLauncher_Hardened": 'Hardened Missile Launcher',
  "Railgun_Hardened": 'Hardened Railway Rifle',
  "SawedOffShotgun_Hardened": 'Hardened Sawed-Off Shotgun',
  "Magnum_Hardened": 'Hardened Scoped .44',
  "Shotgun_Hardened": 'Hardened Shotgun',
  "SniperRifle_Hardened": 'Hardened Sniper Rifle',
  "PipePistol_Heavy": 'Heavy Pipe Pistol',
  "HuntingRifle": 'Hunting Rifle',
  "InstitutePistol_Improved": 'Improved Institute Pistol',
  "InstitutePistol_Incendiary": 'Incendiary Institute Pistol',
  "AssaultRifle_Infiltrator": 'Infiltrator',
  "InstitutePistol": 'Institute Pistol',
  "InstituteRifle": 'Institute Rifle',
  "JunkJet": 'Junk Jet',
  "Melee_KitchenKnife": 'Kitchen Knife',
  "SawedOffShotgun_Kneecapper": 'Kneecapper',
  "LaserMusket": 'Laser Musket',
  "LaserPistol": 'Laser Pistol',
  "LaserRifle": 'Laser Rifle',
  "Minigun_LeadBelcher": 'Lead Belcher',
  "Rifle": 'Lever-Action Rifle',
  "Rifle_LincolnsRepeater": "Lincoln's Repeater",
  "PipePistol_LittleBrother": 'Little Brother',
  "Pistol_LoneWanderer": 'Lone Wanderer',
  "InstituteRifle_Long": 'Long Institute Rifle',
  "PipeRifle_Long": 'Long Pipe Rifle',
  "GaussRifle_Magnetro4000": 'Magnetron 4000',
  "PlasmaRifle_MeanGreenMonster": 'Mean Green Monster',
  "Minigun": 'Minigun',
  "Fatman_Mirv": 'MIRV',
  "MissilLauncher_MissLauncher": 'Miss Launcher',
  "MissilLauncher": 'Missile Launcher',
  "PlasmaPistol_MPLXNovasurge": 'MPXL Novasurge',
  "InstituteRifle_NightVision": 'Night-Vision Institute Rifle',
  "PipeRifle_NightVision": 'Night-Vision Pipe Rifle',
  "HuntingRifle_OlPainless": "Ol' Painless",
  "PlasmaThrower_Overcharged": 'Overcharged Plasma Thrower',
  "Melee_Pickaxe": 'Pickaxe',
  "PipePistol": 'Pipe Pistol',
  "PipeRifle": 'Pipe Rifle',
  "PlasmaPistol": 'Plasma Pistol',
  "PlasmaRifle": 'Plasma Rifle',
  "PlasmaThrower": 'Plasma Thrower',
  "Melee_PoolCue": 'Pool Cue',
  "Flamer_Pressurized": 'Pressurized Flamer',
  "Railgun_Railmaster": 'Railmaster',
  "Railgun": 'Railway Rifle',
  "JunkJet_RecoilCompensated": 'Recoil Compensated Junk Jet',
  "BBGun_RedRocket": 'Red Rocket',
  "Melee_RaiderSword": 'Relentless Raider Sword',
  "032Pistol_Rusty": 'Rusty .32 Pistol',
  "Pistol_Rusty": 'Rusty 10mm Pistol',
  "AlienBlaster_Rusty": 'Rusty Alien Blaster',
  "AssaultRifle_Rusty": 'Rusty Assault Rifle',
  "BBGun_Rusty": 'Rusty BB Gun',
  "CombatShotgun_Rusty": 'Rusty Combat Shotgun',
  "Fatman_Rusty": 'Rusty Fat Man',
  "Flamer_Rusty": 'Rusty Flamer',
  "GatlingLaser_Rusty": 'Rusty Gatling Laser',
  "GaussRifle_Rusty": 'Rusty Gauss Rifle',
  "HuntingRifle_Rusty": 'Rusty Hunting Rifle',
  "LaserPistol_Rusty": 'Rusty Laser Pistol',
  "LaserRifle_Rusty": 'Rusty Laser Rifle',
  "Rifle_Rusty": 'Rusty Lever-Action Rifle',
  "Minigun_Rusty": 'Rusty Minigun',
  "MissilLauncher_Rusty": 'Rusty Missile Launcher',
  "PlasmaPistol_Rusty": 'Rusty Plasma Pistol',
  "PlasmaRifle_Rusty": 'Rusty Plasma Rifle',
  "Railgun_Rusty": 'Rusty Railway Rifle',
  "SawedOffShotgun_Rusty": 'Rusty Sawed-Off Shotgun',
  "Magnum_Rusty": 'Rusty Scoped .44',
  "Shotgun_Rusty": 'Rusty Shotgun',
  "SniperRifle_Rusty": 'Rusty Sniper Rifle',
  "SawedOffShotgun": 'Sawed-Off Shotgun',
  "InstitutePistol_Scattered": 'Scattered Institute Pistol',
  "Magnum": 'Scoped .44',
  "InstitutePistol_Scoped": 'Scoped Institute Pistol',
  "PipePistol_Scoped": 'Scoped Pipe Pistol',
  "Shotgun": 'Shotgun',
  "LaserPistol_SmugglersEnd": "Smuggler's End",
  "SniperRifle": 'Sniper Rifle',
  "JunkJet_Tactical": 'Tactical Junk Jet',
  "PlasmaThrower_Tactical": 'Tactical Plasma Thrower',
  "InstituteRifle_Targeting": 'Targeting Institute Rifle',
  "JunkJet_TechniciansRevenge": "Technician's Revenge",
  "AlienBlaster_Tuned": 'Tuned Alien Blaster',
  "GatlingLaser_Tuned": 'Tuned Gatling Laser',
  "LaserPistol_Tuned": 'Tuned Laser Pistol',
  "LaserRifle_Tuned": 'Tuned Laser Rifle',
  "PlasmaPistol_Tuned": 'Tuned Plasma Pistol',
  "PlasmaRifle_Tuned": 'Tuned Plasma Rifle',
  "GatlingLaser_Vengeance": 'Vengeance',
  "SniperRifle_VictoryRifle": 'Victory Rifle',
  "InstituteRifle_VirgilsRifle": "Virgil's Rifle",
  "LaserRifle_WaserWifle": 'Wazer Wifle',
  "032Pistol_WildBillsSidearm": "Wild Bill's Sidearm"
} as const;