export const WEAPON_LIST = {
  '032Pistol_Rusty': 'Rusty .32 Pistol',
  '032Pistol': '.32 Pistol',
  '032Pistol_Enhanced': 'Enhanced .32 Pistol',
  '032Pistol_Hardened': 'Hardened .32 Pistol',
  '032Pistol_ArmorPiercing': 'Armor Piercing .32 Pistol',
  '032Pistol_WildBillsSidearm': "Wild Bill's Sidearm",
  '50CalMachineGun_ArmorPiercing': 'Armor Piercing .50 Cal Machine Gun',
  'AlienBlaster_Rusty': 'Rusty Alien Blaster',
  'AlienBlaster': 'Alien Blaster',
  'AlienBlaster_Tuned': 'Tuned Alien Blaster',
  'AlienBlaster_Focused': 'Focused Alien Blaster',
  'AlienBlaster_Amplified': 'Amplified Alien Blaster',
  'AlienBlaster_Destabilizer': 'Destabilizer',
  'AmataPistol': "Amata's Pistol",
  'AssaultRifle_Rusty': 'Rusty Assault Rifle',
  'AssaultRifle': 'Assault Rifle',
  'AssaultRifle_Enhanced': 'Enhanced Assault Rifle',
  'AssaultRifle_Hardened': 'Hardened Assault Rifle',
  'AssaultRifle_ArmorPiercing': 'Armor Piercing Assault Rifle',
  'AssaultRifle_Infiltrator': 'Infiltrator',
  'BBGun_Rusty': 'Rusty BB Gun',
  'BBGun': 'BB Gun',
  'BBGun_Enhanced': 'Enhanced BB Gun',
  'BBGun_Hardened': 'Hardened BB Gun',
  'BBGun_ArmorPiercing': 'Armor Piercing BB Gun',
  'BBGun_RedRocket': 'Red Rocket',
  'BOSAssaultRifle_Enhanced': 'Enhanced Brotherhood Assault Rifle',
  'BOSAssaultRifle_ArmorPiercing': 'Armor Piercing Brotherhood Assault Rifle',
  'BumperSword': 'Bumper Sword',
  'CombatShotgun_Rusty': 'Rusty Combat Shotgun',
  'CombatShotgun': 'Combat Shotgun',
  'CombatShotgun_Enhanced': 'Enhanced Combat Shotgun',
  'CombatShotgun_Hardened': 'Hardened Combat Shotgun',
  'CombatShotgun_CharonsShotgun': "Charon's Shotgun",
  'CombatShotgun_DoubleBarrelled': 'Double-Barrel Combat Shotgun',
  'Fatman_Rusty': 'Rusty Fat Man',
  'Fatman': 'Fat Man',
  'Fatman_Enhanced': 'Enhanced Fat Man',
  'Fatman_Hardened': 'Hardened Fat Man',
  'Fatman_Guided': 'Guided Fat Man',
  'Fatman_Mirv': 'MIRV',
  'Fist': 'Fist',
  'Flamer_Rusty': 'Rusty Flamer',
  'Flamer': 'Flamer',
  'Flamer_Enhanced': 'Enhanced Flamer',
  'Flamer_Hardened': 'Hardened Flamer',
  'Flamer_Burnmaster': 'Burnmaster',
  'Flamer_Pressurized': 'Pressurized Flamer',
  'GatlingLaser_Rusty': 'Rusty Gatling Laser',
  'GatlingLaser': 'Gatling Laser',
  'GatlingLaser_Tuned': 'Tuned Gatling Laser',
  'GatlingLaser_Focused': 'Focused Gatling Laser',
  'GatlingLaser_Amplified': 'Amplified Gatling Laser',
  'GatlingLaser_Vengeance': 'Vengeance',
  'GaussPistol_Rusty': 'Rusty Gauss Pistol',
  'GaussPistol_Hardened': 'Hardened Gauss Pistol',
  'GaussRifle_Rusty': 'Rusty Gauss Rifle',
  'GaussRifle': 'Gauss Rifle',
  'GaussRifle_Enhanced': 'Enhanced Gauss Rifle',
  'GaussRifle_Hardened': 'Hardened Gauss Rifle',
  'GaussRifle_Accelerated': 'Accelerated Gauss Rifle',
  'GaussRifle_Magnetro4000': 'Magnetron 4000',
  'GhoulRevolver': 'Ghoul Revolver',
  'HuntingRifle_Rusty': 'Rusty Hunting Rifle',
  'HuntingRifle': 'Hunting Rifle',
  'HuntingRifle_Enhanced': 'Enhanced Hunting Rifle',
  'HuntingRifle_Hardened': 'Hardened Hunting Rifle',
  'HuntingRifle_ArmorPiercing': 'Armor Piercing Hunting Rifle',
  'HuntingRifle_OlPainless': "Ol' Painless",
  'InstitutePistol': 'Institute Pistol',
  'InstitutePistol_Incendiary': 'Incendiary Institute Pistol',
  'InstitutePistol_Improved': 'Improved Institute Pistol',
  'InstitutePistol_Scoped': 'Scoped Institute Pistol',
  'InstitutePistol_Scattered': 'Scattered Institute Pistol',
  'InstitutePistol_Apotheosis': 'Apotheosis',
  'InstituteRifle': 'Institute Rifle',
  'InstituteRifle_Excited': 'Excited Institute Rifle',
  'InstituteRifle_Long': 'Long Institute Rifle',
  'InstituteRifle_NightVision': 'Night-Vision Institute Rifle',
  'InstituteRifle_Targeting': 'Targeting Institute Rifle',
  'InstituteRifle_VirgilsRifle': "Virgil's Rifle",
  'JunkJet': 'Junk Jet',
  'JunkJet_RecoilCompensated': 'Recoil Compensated Junk Jet',
  'JunkJet_Tactical': 'Tactical Junk Jet',
  'JunkJet_Electrified': 'Electrified Junk Jet',
  'JunkJet_Flaming': 'Flaming Junk Jet',
  'JunkJet_TechniciansRevenge': "Technician's Revenge",
  'LaserMusket': 'Laser Musket',
  'LaserPistol_Rusty': 'Rusty Laser Pistol',
  'LaserPistol': 'Laser Pistol',
  'LaserPistol_Tuned': 'Tuned Laser Pistol',
  'LaserPistol_Focused': 'Focused Laser Pistol',
  'LaserPistol_Amplified': 'Amplified Laser Pistol',
  'LaserPistol_SmugglersEnd': "Smuggler's End",
  'LaserRifle_Rusty': 'Rusty Laser Rifle',
  'LaserRifle': 'Laser Rifle',
  'LaserRifle_Tuned': 'Tuned Laser Rifle',
  'LaserRifle_Focused': 'Focused Laser Rifle',
  'LaserRifle_Amplified': 'Amplified Laser Rifle',
  'LaserRifle_WaserWifle': 'Wazer Wifle',
  'LeverActionRifle_Henrietta': 'Henrietta',
  'Magnum_Rusty': 'Rusty Scoped .44',
  'Magnum': 'Scoped .44',
  'Magnum_Enhanced': 'Enhanced Scoped .44',
  'Magnum_Hardened': 'Hardened Scoped .44',
  'Magnum_ArmorPiercing': 'Armor Piercing Scoped .44',
  'Magnum_Blackhawk': 'Blackhawk',
  'Melee_BaseballBat': 'Baseball Bat',
  'Melee_ButcherKnife': 'Butcher Knife',
  'Melee_FireHydrantBat': 'Fire Hydrant Bat',
  'Melee_KitchenKnife': 'Kitchen Knife',
  'Melee_Pickaxe': 'Pickaxe',
  'Melee_PoolCue': 'Pool Cue',
  'Melee_RaiderSword': 'Relentless Raider Sword',
  'Minigun_Rusty': 'Rusty Minigun',
  'Minigun': 'Minigun',
  'Minigun_Enhanced': 'Enhanced Minigun',
  'Minigun_Hardened': 'Hardened Minigun',
  'Minigun_ArmorPiercing': 'Armor Piercing Minigun',
  'Minigun_LeadBelcher': 'Lead Belcher',
  'MissilLauncher_Rusty': 'Rusty Missile Launcher',
  'MissilLauncher': 'Missile Launcher',
  'MissilLauncher_Enhanced': 'Enhanced Missile Launcher',
  'MissilLauncher_Hardened': 'Hardened Missile Launcher',
  'MissilLauncher_Guided': 'Guided Missile Launcher',
  'MissilLauncher_MissLauncher': 'Miss Launcher',
  'PipePistol': 'Pipe Pistol',
  'PipePistol_Auto': 'Auto Pipe Pistol',
  'PipePistol_HairTrigger': 'Hair Trigger Pipe Pistol',
  'PipePistol_Heavy': 'Heavy Pipe Pistol',
  'PipePistol_LittleBrother': 'Little Brother',
  'PipePistol_Scoped': 'Scoped Pipe Pistol',
  'PipeRifle': 'Pipe Rifle',
  'PipeRifle_Bayoneted': 'Bayoneted Pipe Rifle',
  'PipeRifle_BigSister': 'Big Sister',
  'PipeRifle_Calibrated': 'Calibrated Pipe Rifle',
  'PipeRifle_Long': 'Long Pipe Rifle',
  'PipeRifle_NightVision': 'Night-Vision Pipe Rifle',
  'Pistol_Rusty': 'Rusty 10mm Pistol',
  'Pistol': '10mm Pistol',
  'Pistol_Enhanced': 'Enhanced 10mm Pistol',
  'Pistol_Hardened': 'Hardened 10mm Pistol',
  'Pistol_ArmorPiercing': 'Armor Piercing 10mm Pistol',
  'Pistol_LoneWanderer': 'Lone Wanderer',
  'PlasmaPistol_Rusty': 'Rusty Plasma Pistol',
  'PlasmaPistol': 'Plasma Pistol',
  'PlasmaPistol_Tuned': 'Tuned Plasma Pistol',
  'PlasmaPistol_Focused': 'Focused Plasma Pistol',
  'PlasmaPistol_Amplified': 'Amplified Plasma Pistol',
  'PlasmaPistol_MPLXNovasurge': 'MPXL Novasurge',
  'PlasmaRifle_Rusty': 'Rusty Plasma Rifle',
  'PlasmaRifle': 'Plasma Rifle',
  'PlasmaRifle_Tuned': 'Tuned Plasma Rifle',
  'PlasmaRifle_Focused': 'Focused Plasma Rifle',
  'PlasmaRifle_Amplified': 'Amplified Plasma Rifle',
  'PlasmaRifle_MeanGreenMonster': 'Mean Green Monster',
  'PlasmaThrower': 'Plasma Thrower',
  'PlasmaThrower_Agitated': 'Agitated Plasma Thrower',
  'PlasmaThrower_Boosted': 'Boosted Plasma Thrower',
  'PlasmaThrower_DragonsMaw': "Dragon's Maw",
  'PlasmaThrower_Overcharged': 'Overcharged Plasma Thrower',
  'PlasmaThrower_Tactical': 'Tactical Plasma Thrower',
  'PoliceBaton': 'Police Baton',
  'PowerFist': 'Power Fist',
  'PowerFistEd': 'Enhanced Power Fist',
  'Railgun_Rusty': 'Rusty Railway Rifle',
  'Railgun': 'Railway Rifle',
  'Railgun_Enhanced': 'Enhanced Railway Rifle',
  'Railgun_Hardened': 'Hardened Railway Rifle',
  'Railgun_Accelerated': 'Accelerated Railway Rifle',
  'Railgun_Railmaster': 'Railmaster',
  'Rifle_Rusty': 'Rusty Lever-Action Rifle',
  'Rifle': 'Lever-Action Rifle',
  'Rifle_Enhanced': 'Enhanced Lever-Action Rifle',
  'Rifle_Hardened': 'Hardened Lever-Action Rifle',
  'Rifle_ArmorPiercing': 'Armor Piercing Lever-Action Rifle',
  'Rifle_LincolnsRepeater': "Lincoln's Repeater",
  'Ripper_Rusty': 'Rusty Ripper',
  'Ripper': 'Ripper',
  'SawedOffShotgun_Rusty': 'Rusty Sawed-Off Shotgun',
  'SawedOffShotgun': 'Sawed-Off Shotgun',
  'SawedOffShotgun_Enhanced': 'Enhanced Sawed-Off Shotgun',
  'SawedOffShotgun_Hardened': 'Hardened Sawed-Off Shotgun',
  'SawedOffShotgun_DoubleBarrelled': 'Double-Barrel Sawed-Off Shotgun',
  'SawedOffShotgun_Kneecapper': 'Kneecapper',
  'Shotgun_Rusty': 'Rusty Shotgun',
  'Shotgun': 'Shotgun',
  'Shotgun_Enhanced': 'Enhanced Shotgun',
  'Shotgun_Hardened': 'Hardened Shotgun',
  'Shotgun_DoubleBarrelled': 'Double-Barrel Shotgun',
  'Shotgun_FarmersDaughter': "Farmer's Daughter",
  'SniperRifle_Rusty': 'Rusty Sniper Rifle',
  'SniperRifle': 'Sniper Rifle',
  'SniperRifle_Enhanced': 'Enhanced Sniper Rifle',
  'SniperRifle_Hardened': 'Hardened Sniper Rifle',
  'SniperRifle_ArmorPiercing': 'Armor Piercing Sniper Rifle',
  'SniperRifle_VictoryRifle': 'Victory Rifle',
  'SurgicalRipper': 'Surgical Ripper',
  'SurgicalRipper_Enhanced': 'Enhanced Surgical Ripper',
  'T60Pistol': 'T-60 Pistol',
  'T60Pistol_ArmorPiercing': 'Armor Piercing T-60 Pistol',
} as const;
